// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Maintenance.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Maintenance.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    [Migration("20260707074519_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("maintenance")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MachineId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OperatingHours")
                        .HasColumnType("decimal(15,2)");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_assets_facility_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assets_tenant_id");

                    b.ToTable("assets", "maintenance");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedPartnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("AssignmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PostponementReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresDowntime")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_work_orders_asset_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_orders_tenant_id");

                    b.ToTable("work_orders", "maintenance");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.Asset", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Maintenance.Domain.ValueObjects.MaintenancePlan", "MaintenancePlans", b1 =>
                        {
                            b1.Property<Guid>("asset_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<Guid?>("AssigneeEmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("assignee_employee_id");

                            b1.Property<string>("AssigneeType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("assignee_type");

                            b1.Property<decimal>("EstimatedHours")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("estimated_hours");

                            b1.Property<int?>("IntervalDays")
                                .HasColumnType("integer")
                                .HasColumnName("interval_days");

                            b1.Property<decimal?>("IntervalHours")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("interval_hours");

                            b1.Property<string>("Label")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("label");

                            b1.Property<DateOnly?>("LastDone")
                                .HasColumnType("date")
                                .HasColumnName("last_done");

                            b1.Property<decimal?>("LastDoneHours")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("last_done_hours");

                            b1.Property<string>("Trigger")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("trigger");

                            b1.HasKey("asset_id", "Id");

                            b1.HasIndex("asset_id")
                                .HasDatabaseName("ix_asset_maintenance_plans_asset_id");

                            b1.ToTable("asset_maintenance_plans", "maintenance");

                            b1.WithOwner()
                                .HasForeignKey("asset_id");
                        });

                    b.Navigation("MaintenancePlans");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.WorkOrder", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Maintenance.Domain.ValueObjects.WorkOrderPart", "Parts", b1 =>
                        {
                            b1.Property<Guid>("work_order_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasColumnType("text");

                            b1.Property<string>("CatalogCode")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("catalog_code");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("work_order_id", "Id");

                            b1.HasIndex("work_order_id")
                                .HasDatabaseName("ix_work_order_parts_work_order_id");

                            b1.ToTable("work_order_parts", "maintenance");

                            b1.WithOwner()
                                .HasForeignKey("work_order_id");

                            b1.OwnsOne("SpaceOS.Modules.Maintenance.Domain.ValueObjects.Money", "UnitPrice", b2 =>
                                {
                                    b2.Property<Guid>("WorkOrderPartwork_order_id")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("WorkOrderPartId")
                                        .HasColumnType("text");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("decimal(10,2)")
                                        .HasColumnName("unit_price_amount");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("unit_price_currency");

                                    b2.HasKey("WorkOrderPartwork_order_id", "WorkOrderPartId");

                                    b2.ToTable("work_order_parts", "maintenance");

                                    b2.WithOwner()
                                        .HasForeignKey("WorkOrderPartwork_order_id", "WorkOrderPartId");
                                });

                            b1.Navigation("UnitPrice")
                                .IsRequired();
                        });

                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
