// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Maintenance.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Maintenance.Migrations
{
    [DbContext(typeof(MaintenanceDbContext))]
    partial class MaintenanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("uuid")
                        .HasColumnName("facility_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("kind");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("location");

                    b.Property<string>("MachineId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("machine_id");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("OperatingHours")
                        .HasColumnType("numeric(15,2)")
                        .HasColumnName("operating_hours");

                    b.Property<bool>("Retired")
                        .HasColumnType("boolean")
                        .HasColumnName("retired");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("VehicleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vehicle_id");

                    b.Property<string>("Vendor")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("vendor");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId")
                        .HasDatabaseName("ix_assets_facility_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_assets_tenant_id");

                    b.ToTable("assets", "maintenance");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.WorkOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignedEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_employee_id");

                    b.Property<Guid?>("AssignedPartnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_partner_id");

                    b.Property<string>("AssignmentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignment_type");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("actual_hours");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("priority");

                    b.Property<string>("PostponementReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("postponement_reason");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("rejection_reason");

                    b.Property<bool>("RequiresDowntime")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_downtime");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("type");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.HasKey("Id");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_work_orders_asset_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_work_orders_tenant_id");

                    b.ToTable("work_orders", "maintenance");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.ValueObjects.MaintenancePlan", b =>
                {
                    b.HasKey("AssetId", "Id")
                        .HasName("PK_asset_maintenance_plans");

                    b.ToTable("asset_maintenance_plans", "maintenance");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeEmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_employee_id");

                    b.Property<string>("AssigneeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("assignee_type");

                    b.Property<decimal>("EstimatedHours")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("estimated_hours");

                    b.Property<int?>("IntervalDays")
                        .HasColumnType("integer")
                        .HasColumnName("interval_days");

                    b.Property<decimal?>("IntervalHours")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("interval_hours");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("label");

                    b.Property<DateTime?>("LastDone")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_done");

                    b.Property<decimal?>("LastDoneHours")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("last_done_hours");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("trigger");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_maintenance_plans_asset_id");

                    b.HasOne("SpaceOS.Modules.Maintenance.Domain.Aggregates.Asset")
                        .WithMany("MaintenancePlans")
                        .HasForeignKey("AssetId");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.ValueObjects.WorkOrderPart", b =>
                {
                    b.HasKey("WorkOrderId", "Id")
                        .HasName("PK_work_order_parts");

                    b.ToTable("work_order_parts", "maintenance");

                    b.Property<Guid>("WorkOrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("work_order_id");

                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("CatalogCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("catalog_code");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.HasIndex("WorkOrderId")
                        .HasDatabaseName("ix_work_order_parts_work_order_id");

                    b.HasOne("SpaceOS.Modules.Maintenance.Domain.Aggregates.WorkOrder")
                        .WithMany("Parts")
                        .HasForeignKey("WorkOrderId");

                    b.OwnsOne("SpaceOS.Kernel.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<decimal>("Amount")
                                .HasColumnType("numeric(10,2)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency");

                            b1.HasKey();

                            b1.ToTable("work_order_parts");

                            b1.WithOwner();
                        });
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.Asset", b =>
                {
                    b.Navigation("MaintenancePlans");
                });

            modelBuilder.Entity("SpaceOS.Modules.Maintenance.Domain.Aggregates.WorkOrder", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
