// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceOS.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260415060000_Migration_0030_AddAuditEventSequence")]
    partial class Migration_0030_AddAuditEventSequence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Aggregates.PhysicalSpace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CellSizeMm")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegistrationHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SpaceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.ComplexProperty<Dictionary<string, object>>("Dimensions", "SpaceOS.Kernel.Domain.Aggregates.PhysicalSpace.Dimensions#DimensionVector", b1 =>
                        {
                            b1.Property<int>("DepthMm")
                                .HasColumnType("INTEGER")
                                .HasColumnName("DepthMm");

                            b1.Property<int>("HeightMm")
                                .HasColumnType("INTEGER")
                                .HasColumnName("HeightMm");

                            b1.Property<int>("WidthMm")
                                .HasColumnType("INTEGER")
                                .HasColumnName("WidthMm");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Origin", "SpaceOS.Kernel.Domain.Aggregates.PhysicalSpace.Origin#Point3D", b1 =>
                        {
                            b1.Property<int>("X")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OriginX");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OriginY");

                            b1.Property<int>("Z")
                                .HasColumnType("INTEGER")
                                .HasColumnName("OriginZ");
                        });

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("PhysicalSpaces", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_RefreshTokens_ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UQ_RefreshTokens_TokenHash");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.BvhNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ElementId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsLeaf")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PhysicalSpaceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("PhysicalSpaceId");

                    b.ToTable("BvhNodes", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Facilities", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.FlowEpic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrentStageCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProofUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StageChainTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetFacilityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetFacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("FlowEpics", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.SpaceLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAuthTokenRef")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentDataJson")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalNode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastStateHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("SpaceLayers", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.SpatialElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BvhLeafId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowEpicId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BvhLeafId")
                        .IsUnique();

                    b.HasIndex("FlowEpicId");

                    b.HasIndex("TenantId");

                    b.ToTable("SpatialElements", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.SpatialTaskLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowTaskId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SpatialElementId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkPhase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FlowTaskId");

                    b.HasIndex("SpatialElementId");

                    b.HasIndex("FlowTaskId", "SpatialElementId")
                        .IsUnique();

                    b.ToTable("SpatialTaskLinks", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.StageChainStep", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ChainTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StageCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("StageDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChainTemplateId");

                    b.HasIndex("StageDefinitionId");

                    b.HasIndex("ChainTemplateId", "SortOrder")
                        .IsUnique();

                    b.HasIndex("ChainTemplateId", "StageCode")
                        .IsUnique();

                    b.ToTable("StageChainSteps", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.StageChainTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "Name")
                        .IsUnique();

                    b.ToTable("StageChainTemplates", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.StageDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModuleEndpoint")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("StageCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "StageCode")
                        .IsUnique();

                    b.ToTable("StageDefinitions", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.StageHandoff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowEpicId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HandshakeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashAlgorithm")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SourceActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceStageCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TargetActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetStageCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FlowEpicId");

                    b.HasIndex("FlowEpicId", "IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("TenantId", "SourceStageCode");

                    b.HasIndex("TenantId", "TargetStageCode");

                    b.HasIndex("FlowEpicId", "SourceStageCode", "TargetStageCode", "Version")
                        .IsUnique();

                    b.ToTable("StageHandoffs", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrandSkinId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(32)")
                        .HasDefaultValue("Manufacturer")
                        .HasColumnName("TenantType");

                    b.Property<string>("_enabledModules")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("EnabledModules")
                        .HasDefaultValueSql("'[]'");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.TenantHandshakeAllowlist", b =>
                {
                    b.Property<Guid>("GuestTenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HostTenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("_allowedTradeTypes")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("AllowedTradeTypes");

                    b.HasKey("GuestTenantId", "HostTenantId");

                    b.ToTable("TenantHandshakeAllowlist", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.WorkStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkStations", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Federation.NodeManifest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxGuestLod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicApiVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ServerUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("NodeManifests", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("TenantId");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Snapshots.AggregateSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AggregateType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("SnapshotAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TriggerEventId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId");

                    b.HasIndex("TenantId");

                    b.ToTable("AggregateSnapshots", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Sync.SyncSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ClientSignalId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EpicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSyncedToKernel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EpicId")
                        .HasDatabaseName("IX_sync_signals_epic");

                    b.HasIndex("TenantId", "ClientSignalId")
                        .IsUnique();

                    b.HasIndex("TenantId", "OccurredAt")
                        .HasDatabaseName("IX_sync_signals_tenant_occurred");

                    b.ToTable("SyncSignals", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.UserProfiles.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsErased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ExternalUserId", "TenantId")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.BvhNode", b =>
                {
                    b.HasOne("SpaceOS.Kernel.Domain.Entities.BvhNode", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SpaceOS.Kernel.Domain.ValueObjects.BoundingBox", "BoundingBox", b1 =>
                        {
                            b1.Property<Guid>("BvhNodeId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("MaxX")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxX");

                            b1.Property<int>("MaxY")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxY");

                            b1.Property<int>("MaxZ")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MaxZ");

                            b1.Property<int>("MinX")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MinX");

                            b1.Property<int>("MinY")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MinY");

                            b1.Property<int>("MinZ")
                                .HasColumnType("INTEGER")
                                .HasColumnName("MinZ");

                            b1.HasKey("BvhNodeId");

                            b1.ToTable("BvhNodes");

                            b1.WithOwner()
                                .HasForeignKey("BvhNodeId");
                        });

                    b.Navigation("BoundingBox")
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.FlowEpic", b =>
                {
                    b.OwnsOne("SpaceOS.Kernel.Domain.ValueObjects.B2BHandshake", "Handshake", b1 =>
                        {
                            b1.Property<Guid>("FlowEpicId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ContractHash")
                                .HasMaxLength(64)
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_ContractHash");

                            b1.Property<DateTimeOffset>("DelegatedOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_DelegatedOn");

                            b1.Property<Guid>("GuestTenantId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_GuestTenantId");

                            b1.Property<string>("InitiatorAnchorJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_InitiatorAnchorJson");

                            b1.Property<string>("ResponsibleAnchorJson")
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_ResponsibleAnchorJson");

                            b1.Property<string>("VisibilityScope")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_VisibilityScope");

                            b1.HasKey("FlowEpicId");

                            b1.ToTable("FlowEpics");

                            b1.WithOwner()
                                .HasForeignKey("FlowEpicId");
                        });

                    b.Navigation("Handshake");
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.StageChainStep", b =>
                {
                    b.HasOne("SpaceOS.Kernel.Domain.Entities.StageChainTemplate", null)
                        .WithMany("Steps")
                        .HasForeignKey("ChainTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpaceOS.Kernel.Domain.Entities.StageDefinition", null)
                        .WithMany()
                        .HasForeignKey("StageDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.StageChainTemplate", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
