// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceOS.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407140000_Migration_0019_SpatialTaskLinks")]
    partial class Migration_0019_SpatialTaskLinks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal stub
        }
    }
}
