// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceOS.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260410130000_Migration_0028_StageRegistry")]
    partial class Migration_0028_StageRegistry
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal stub — Stage Registry tables (StageDefinitions, StageChainTemplates,
            // StageChainSteps, StageHandoffs) are raw-SQL managed, not EF Core entities.
        }
    }
}
