// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceOS.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260402085938_AddIsArchivedToAllEntities")]
    partial class AddIsArchivedToAllEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("SpaceOS.Kernel.Domain.AuditLog.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StateHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.Facility", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Facilities", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.FlowEpic", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetFacilityId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TargetFacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("FlowEpics", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.SpaceLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalAuthToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalSourceUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntentDataJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExternalNode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastStateHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("SpaceLayers", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.WorkStation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FacilityId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TenantId");

                    b.ToTable("WorkStations", (string)null);
                });

            modelBuilder.Entity("SpaceOS.Kernel.Domain.Entities.FlowEpic", b =>
                {
                    b.OwnsOne("SpaceOS.Kernel.Domain.ValueObjects.B2BHandshake", "Handshake", b1 =>
                        {
                            b1.Property<Guid>("FlowEpicId")
                                .HasColumnType("TEXT");

                            b1.Property<DateTimeOffset>("DelegatedOn")
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_DelegatedOn");

                            b1.Property<Guid>("GuestTenantId")
                                .HasColumnType("TEXT")
                                .HasColumnName("Handshake_GuestTenantId");

                            b1.HasKey("FlowEpicId");

                            b1.ToTable("FlowEpics");

                            b1.WithOwner()
                                .HasForeignKey("FlowEpicId");
                        });

                    b.Navigation("Handshake");
                });
#pragma warning restore 612, 618
        }
    }
}
