// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceOS.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408120000_Migration_0027_AuditHashesWorm")]
    partial class Migration_0027_AuditHashesWorm
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // Minimal stub — AuditHashes is a raw-SQL managed table, not an EF Core entity.
        }
    }
}
