#!/bin/bash
# Blocker Alert & Escalation
# Purpose: Auto-detect BLOCKED messages, calculate age, trigger escalation
# Impact: HIGH (prevents 24h+ blockers, ensures timely resolution)
# Difficulty: LOW-MEDIUM
# Author: Explorer Task Research (2026-07-07)
# Usage: Run via cron every 2 hours or on-demand

set -euo pipefail

# Configuration
TERMINAL_BASE="/opt/spaceos/terminals"
TERMINALS=("root" "conductor" "architect" "librarian" "explorer" "backend" "frontend" "designer" "monitor")
LOG_FILE="/opt/spaceos/logs/blocker-alerts.log"
ALERT_THRESHOLD_HOURS=4
CRITICAL_THRESHOLD_HOURS=24
ESCALATION_WEBHOOK="https://datahaven.joinerytech.hu/api/alerts/blocker"

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m'

# Logging
log() {
  echo "[$(date +%Y-%m-%d\ %H:%M:%S)] $1" | tee -a "$LOG_FILE"
}

# Calculate file age in hours
get_file_age_hours() {
  local file=$1
  local file_timestamp=$(stat -c%Y "$file" 2>/dev/null || echo 0)
  local current_timestamp=$(date +%s)
  local age_seconds=$((current_timestamp - file_timestamp))
  local age_hours=$((age_seconds / 3600))
  echo "$age_hours"
}

# Send escalation alert
send_escalation() {
  local terminal=$1
  local file=$2
  local age_hours=$3
  local severity=$4
  local message=$5

  log "$severity: $message"

  # Send to Datahaven webhook
  if command -v curl &> /dev/null; then
    curl -X POST "$ESCALATION_WEBHOOK" \
      -H "Authorization: Bearer dev-token-spaceos-dashboard-2026" \
      -H "Content-Type: application/json" \
      -d "{
        \"terminal\": \"$terminal\",
        \"file\": \"$(basename "$file")\",
        \"age_hours\": $age_hours,
        \"severity\": \"$severity\",
        \"message\": \"$message\",
        \"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"
      }" \
      --silent --show-error || log "⚠️  Webhook delivery failed"
  fi

  # Create escalation inbox message for Conductor (if critical)
  if [ "$severity" == "CRITICAL" ]; then
    create_escalation_message "$terminal" "$file" "$age_hours"
  fi
}

# Create escalation inbox message
create_escalation_message() {
  local terminal=$1
  local blocked_file=$2
  local age_hours=$3

  local msg_id=$(printf "%03d" $(($(ls -1 "$TERMINAL_BASE/conductor/inbox"/*.md 2>/dev/null | wc -l) + 1)))
  local filename="$(date +%Y-%m-%d)_${msg_id}_blocker-escalation-$terminal.md"
  local filepath="$TERMINAL_BASE/conductor/inbox/$filename"

  log "📩 Creating escalation message for Conductor: $filename"

  cat > "$filepath" <<EOF
---
id: MSG-CONDUCTOR-$msg_id
from: blocker-detector
to: conductor
type: escalation
priority: critical
status: UNREAD
model: sonnet
created: $(date +%Y-%m-%d)
---

# Blocker Escalation: $terminal

## Alert
**Terminal:** $terminal
**Blocked File:** $(basename "$blocked_file")
**Age:** ${age_hours}h (threshold: $CRITICAL_THRESHOLD_HOURS h)
**Status:** CRITICAL — Requires immediate attention

## Blocker Details
\`\`\`
$(head -30 "$blocked_file")
\`\`\`

## Recommended Actions
1. Review blocker reason in file: \`$blocked_file\`
2. Classify blocker type:
   - **Technical:** Backend/Frontend can resolve
   - **Infrastructure:** Infra terminal task
   - **Architectural:** Architect consultation needed
   - **Business:** Root decision required
3. Dispatch resolution task to appropriate terminal
4. Update blocker status (escalated → in_progress → resolved)

## Escalation Rules
- **4h:** Alert notification (Conductor monitors)
- **24h:** Critical escalation (this message)
- **48h:** Emergency Root intervention

---

**Generated by:** blocker-detector.sh
**Timestamp:** $(date -u +%Y-%m-%dT%H:%M:%SZ)
EOF

  log "✅ Escalation message created: $filepath"
}

# Check if blocker was resolved (DONE file exists)
is_blocker_resolved() {
  local blocked_file=$1
  local outbox_dir=$(dirname "$blocked_file")

  # Extract the base task ID from BLOCKED file (e.g., MSG-BACKEND-184-BLOCKED → MSG-BACKEND-184)
  local blocked_id=$(grep "^id:" "$blocked_file" 2>/dev/null | head -1 | sed 's/id: //' | sed 's/-BLOCKED$//')

  # Also check ref field (e.g., ref: MSG-BACKEND-184)
  local ref_id=$(grep "^ref:" "$blocked_file" 2>/dev/null | head -1 | sed 's/ref: //')

  # Check for DONE file with either ID pattern
  local done_count=0
  if [ -n "$blocked_id" ]; then
    done_count=$((done_count + $(find "$outbox_dir" -type f -name "*${blocked_id}*" 2>/dev/null | grep -iE "(done|complete)" | wc -l)))
  fi
  if [ -n "$ref_id" ] && [ "$ref_id" != "$blocked_id" ]; then
    done_count=$((done_count + $(find "$outbox_dir" -type f -name "*${ref_id}*" 2>/dev/null | grep -iE "(done|complete)" | wc -l)))
  fi

  # Also check inbox for completed status
  local inbox_dir="${outbox_dir%/outbox}/inbox"
  if [ -n "$ref_id" ] && [ -d "$inbox_dir" ]; then
    local inbox_status=$(grep -l "$ref_id" "$inbox_dir"/*.md 2>/dev/null | head -1 | xargs grep "^status:" 2>/dev/null | head -1 || echo "")
    if echo "$inbox_status" | grep -qiE "(completed|done)"; then
      done_count=$((done_count + 1))
    fi
  fi

  [ "$done_count" -gt 0 ]
}

# Check if escalation was already sent for this blocker (duplicate prevention)
is_duplicate_escalation() {
  local blocked_file=$1

  # Extract the base task ID from BLOCKED file
  local blocked_id=$(grep "^id:" "$blocked_file" 2>/dev/null | head -1 | sed 's/id: //' | sed 's/-BLOCKED$//')
  local ref_id=$(grep "^ref:" "$blocked_file" 2>/dev/null | head -1 | sed 's/ref: //')

  # Use the most specific ID available
  local search_id="$blocked_id"
  [ -n "$ref_id" ] && search_id="$ref_id"

  # Check if any escalation for Conductor contains this MSG-ID within last 7 days
  local escalation_count=0
  if [ -n "$search_id" ]; then
    escalation_count=$(find "$TERMINAL_BASE/conductor/inbox" -type f -name "*.md" -mtime -7 2>/dev/null | xargs grep -l "$search_id" 2>/dev/null | wc -l)
  fi

  [ "$escalation_count" -gt 0 ]
}

# Main blocker detection
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "🔍 Blocker Detection & Escalation - $(date +%Y-%m-%d\ %H:%M:%S)"
log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

total_blockers=0
critical_blockers=0
alert_blockers=0
resolved_blockers=0

for terminal in "${TERMINALS[@]}"; do
  outbox_path="$TERMINAL_BASE/$terminal/outbox"

  # Skip if outbox doesn't exist
  if [ ! -d "$outbox_path" ]; then
    continue
  fi

  # Find BLOCKED messages (last 7 days)
  while IFS= read -r file; do
    [ -z "$file" ] && continue

    # CHECK IF BLOCKER WAS RESOLVED (DONE file exists)
    if is_blocker_resolved "$file"; then
      resolved_blockers=$((resolved_blockers + 1))
      log "✅ RESOLVED: $(basename "$file") - DONE file exists, skipping escalation"
      continue
    fi

    # CHECK IF ESCALATION ALREADY SENT (duplicate prevention)
    if is_duplicate_escalation "$file"; then
      resolved_blockers=$((resolved_blockers + 1))
      log "⏭️  DUPLICATE: $(basename "$file") - escalation already sent within 7 days, skipping"
      continue
    fi

    age_hours=$(get_file_age_hours "$file")
    total_blockers=$((total_blockers + 1))

    if [ "$age_hours" -gt "$CRITICAL_THRESHOLD_HOURS" ]; then
      # CRITICAL: >24h blocked
      critical_blockers=$((critical_blockers + 1))
      message="CRITICAL: $(basename "$file") blocked for ${age_hours}h → Escalate to Root/Conductor"
      echo -e "${RED}🚨 $message${NC}"
      send_escalation "$terminal" "$file" "$age_hours" "CRITICAL" "$message"

    elif [ "$age_hours" -gt "$ALERT_THRESHOLD_HOURS" ]; then
      # ALERT: >4h blocked
      alert_blockers=$((alert_blockers + 1))
      message="Alert: $(basename "$file") blocked for ${age_hours}h → Notify Conductor"
      echo -e "${YELLOW}⚠️  $message${NC}"
      send_escalation "$terminal" "$file" "$age_hours" "ALERT" "$message"

    else
      # INFO: <4h blocked (normal)
      echo -e "${GREEN}ℹ️  $terminal: $(basename "$file") blocked for ${age_hours}h (monitoring)${NC}"
    fi

  done < <(find "$outbox_path" -name "*BLOCKED*.md" -mtime -7 2>/dev/null)
done

log "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
log "📊 Summary: $total_blockers active blockers, $resolved_blockers resolved (skipped)"
log "   Critical: $critical_blockers, Alerts: $alert_blockers"

if [ $critical_blockers -gt 0 ]; then
  log "🚨 CRITICAL: $critical_blockers blocker(s) require immediate escalation"
  exit 1
elif [ $alert_blockers -gt 0 ]; then
  log "⚠️  ALERT: $alert_blockers blocker(s) require attention"
  exit 0
else
  log "✅ No critical blockers detected"
  exit 0
fi
