// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Inventory.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spaceos_inventory")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.MaterialCatalog", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<string>("Description").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("MaterialType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<Guid?>("PreferredSupplierId").HasColumnType("uuid");
                b.Property<int>("ReorderPoint").HasDefaultValue(5).HasColumnType("integer");
                b.Property<decimal>("StandardHeight").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<decimal>("StandardWidth").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<int>("SuggestedOrderQuantity").HasDefaultValue(10).HasColumnType("integer");
                b.Property<string>("SupplierRef").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<decimal>("ThicknessMm").HasPrecision(5, 1).HasColumnType("numeric(5,1)");
                b.Property<decimal>("UnitCost").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
                b.Property<string>("UnitOfMeasure").IsRequired().HasMaxLength(20).HasDefaultValue("pcs").HasColumnType("character varying(20)");
                b.HasKey("Id");
                b.HasIndex("MaterialType").IsUnique();
                b.ToTable("MaterialCatalogs", "spaceos_inventory");
                b.HasData(
                    new { Id = new Guid("10000000-0000-0000-0000-000000000001"), MaterialType = "MDF 18mm", Description = "MDF lap 18mm", StandardWidth = 2800m, StandardHeight = 2070m, ThicknessMm = 18m, UnitCost = 8500m, SupplierRef = "MDF-18", ReorderPoint = 5, SuggestedOrderQuantity = 10, UnitOfMeasure = "pcs", PreferredSupplierId = (Guid?)null },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000002"), MaterialType = "MDF 16mm", Description = "MDF lap 16mm", StandardWidth = 2800m, StandardHeight = 2070m, ThicknessMm = 16m, UnitCost = 7800m, SupplierRef = "MDF-16", ReorderPoint = 5, SuggestedOrderQuantity = 10, UnitOfMeasure = "pcs", PreferredSupplierId = (Guid?)null },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000003"), MaterialType = "HDF 3mm", Description = "HDF lap 3mm", StandardWidth = 2800m, StandardHeight = 2070m, ThicknessMm = 3m, UnitCost = 3200m, SupplierRef = "HDF-3", ReorderPoint = 5, SuggestedOrderQuantity = 10, UnitOfMeasure = "pcs", PreferredSupplierId = (Guid?)null },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000004"), MaterialType = "Forgácslap 18mm", Description = "Forgácslap 18mm", StandardWidth = 2800m, StandardHeight = 2070m, ThicknessMm = 18m, UnitCost = 5500m, SupplierRef = "PART-18", ReorderPoint = 5, SuggestedOrderQuantity = 10, UnitOfMeasure = "pcs", PreferredSupplierId = (Guid?)null },
                    new { Id = new Guid("10000000-0000-0000-0000-000000000005"), MaterialType = "ABS él 0.8mm", Description = "ABS élzáró szalag 0.8mm", StandardWidth = 50m, StandardHeight = 25000m, ThicknessMm = 0.8m, UnitCost = 1200m, SupplierRef = "ABS-08", ReorderPoint = 5, SuggestedOrderQuantity = 10, UnitOfMeasure = "pcs", PreferredSupplierId = (Guid?)null }
                );
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.PanelStock", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<decimal>("HeightMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<string>("LocationCode").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<Guid>("MaterialCatalogId").HasColumnType("uuid");
                b.Property<int>("Quantity").HasColumnType("integer");
                b.Property<string>("StockType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.Property<decimal>("WidthMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("TenantId", "MaterialCatalogId");
                b.ToTable("PanelStocks", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.Offcut", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CuttingJobId").HasColumnType("uuid");
                b.Property<decimal>("HeightMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<string>("MaterialCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<Guid>("MaterialCatalogId").HasColumnType("uuid");
                b.Property<Guid?>("OriginCuttingSheetId").HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<decimal>("ThicknessMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.Property<decimal>("VolumeM3").HasPrecision(18, 9).HasColumnType("numeric(18,9)");
                b.Property<decimal>("WeightKg").HasPrecision(10, 3).HasColumnType("numeric(10,3)");
                b.Property<decimal>("WidthMm").HasPrecision(10, 2).HasColumnType("numeric(10,2)");
                b.Property<DateTime?>("UsedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UsedInJobId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("TenantId", "Status");
                b.HasIndex("Status", "CreatedAt");
                b.HasIndex("VolumeM3");
                b.ToTable("Offcuts", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.OffcutReservation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("OffcutId").IsRequired().HasColumnType("uuid");
                b.Property<Guid>("JobId").IsRequired().HasColumnType("uuid");
                b.Property<Guid>("TenantId").IsRequired().HasColumnType("uuid");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<DateTime>("ExpiresAt").IsRequired().HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("OffcutId");
                b.HasIndex("TenantId", "Status");
                b.HasIndex("ExpiresAt");
                b.ToTable("OffcutReservations", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.StockMovement", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("MaterialCatalogId").HasColumnType("uuid");
                b.Property<string>("MovementType").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<DateTime>("OccurredAt").HasColumnType("timestamp with time zone");
                b.Property<decimal>("Quantity").HasPrecision(10, 4).HasColumnType("numeric(10,4)");
                b.Property<string>("Reference").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("TenantId", "OccurredAt");
                b.ToTable("StockMovements", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.Reservation", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("TenantId").IsRequired().HasColumnType("uuid");
                b.Property<Guid>("CorrelationId").IsRequired().HasColumnType("uuid");
                b.Property<string>("ConsumerModule").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<string>("ConsumerContextJson").IsRequired(false).HasColumnType("jsonb");
                b.Property<Guid?>("CreatedByUserId").IsRequired(false).HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("ExpiresAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<int>("Status").IsRequired().HasColumnType("integer");
                b.Property<uint>("RowVersion").IsRowVersion().IsConcurrencyToken().HasColumnName("xmin").HasColumnType("xid").ValueGeneratedOnAddOrUpdate();
                b.HasKey("Id");
                b.HasIndex("TenantId", "CorrelationId");
                b.ToTable("Reservations", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.ReservationItem", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("ReservationId").IsRequired().HasColumnType("uuid");
                b.Property<Guid>("TenantId").IsRequired().HasColumnType("uuid");
                b.Property<Guid>("StockItemId").IsRequired().HasColumnType("uuid");
                b.Property<string>("MaterialCode").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<decimal>("QuantityReserved").HasPrecision(18, 4).HasColumnType("numeric(18,4)");
                b.Property<decimal>("QuantityConsumed").HasPrecision(18, 4).HasDefaultValue(0m).HasColumnType("numeric(18,4)");
                b.HasKey("Id");
                b.HasIndex("TenantId");
                b.HasIndex("StockItemId");
                b.HasIndex("ReservationId");
                b.ToTable("ReservationItems", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.ReservationItem", b =>
            {
                b.HasOne("SpaceOS.Modules.Inventory.Domain.Aggregates.Reservation", null)
                 .WithMany()
                 .HasForeignKey("ReservationId")
                 .OnDelete(DeleteBehavior.Cascade)
                 .IsRequired();
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.OffcutBatch", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("SourceId").IsRequired().HasColumnType("uuid");
                b.Property<string>("SourceType").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                b.Property<Guid>("TenantId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("TenantId", "SourceType", "SourceId").IsUnique();
                b.ToTable("OffcutBatches", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.InventoryInboundInbox", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("TenantId").IsRequired().HasColumnType("uuid");
                b.Property<Guid>("DeliveryLineId").IsRequired().HasColumnType("uuid");
                b.Property<string>("MaterialCode").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<decimal>("Quantity").HasPrecision(14, 4).HasColumnType("numeric(14,4)");
                b.Property<string>("UnitOfMeasure").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid>("SupplierId").HasColumnType("uuid");
                b.Property<DateTimeOffset>("ReceivedAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("ProcessedAt").IsRequired().HasColumnType("timestamp with time zone");
                b.HasKey("Id");
                b.HasIndex("TenantId", "DeliveryLineId").IsUnique();
                b.ToTable("InventoryInboundInboxes", "spaceos_inventory");
            });

            modelBuilder.Entity("SpaceOS.Modules.Inventory.Domain.Aggregates.InventoryReorderOutbox", b =>
            {
                b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                b.Property<Guid>("TenantId").IsRequired().HasColumnType("uuid");
                b.Property<string>("Payload").IsRequired().HasColumnType("text");
                b.Property<string>("Status").IsRequired().HasMaxLength(20).HasDefaultValue("Pending").HasColumnType("character varying(20)");
                b.Property<DateTimeOffset>("CreatedAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset>("NextAttemptAt").IsRequired().HasColumnType("timestamp with time zone");
                b.Property<DateTimeOffset?>("LeaseUntil").HasColumnType("timestamp with time zone");
                b.Property<int>("AttemptCount").HasDefaultValue(0).HasColumnType("integer");
                b.Property<string>("LastError").HasMaxLength(2000).HasColumnType("character varying(2000)");
                b.HasKey("Id");
                b.HasIndex("Status", "NextAttemptAt");
                b.HasIndex("TenantId");
                b.ToTable("InventoryReorderOutboxes", "spaceos_inventory");
            });
#pragma warning restore 612, 618
        }
    }
}
