// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.QA.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.QA.src.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QADbContext))]
    [Migration("20260707080249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.Inspection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CheckpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("checkpoint_id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PlannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("result");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("CheckpointId")
                        .HasDatabaseName("ix_inspections_checkpoint_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_inspections_tenant_id");

                    b.ToTable("inspections", "qa");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.QACheckpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CheckpointType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("checkpoint_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CriticalLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("critical_level");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_qa_checkpoints_tenant_id");

                    b.ToTable("qa_checkpoints", "qa");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.Inspection", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.QA.Domain.ValueObjects.FailureNote", "FailureNotes", b1 =>
                        {
                            b1.Property<Guid>("inspection_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.Property<string>("FailureType")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("failure_type");

                            b1.Property<string>("PhotoUrl")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("photo_url");

                            b1.HasKey("inspection_id", "Id");

                            b1.HasIndex("inspection_id")
                                .HasDatabaseName("ix_inspection_defects_inspection_id");

                            b1.ToTable("inspection_defects", "qa");

                            b1.WithOwner()
                                .HasForeignKey("inspection_id");
                        });

                    b.Navigation("FailureNotes");
                });

            modelBuilder.Entity("SpaceOS.Modules.QA.Domain.Aggregates.QACheckpoint", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.QA.Domain.ValueObjects.InspectionCriteria", "Criteria", b1 =>
                        {
                            b1.Property<Guid>("qa_checkpoint_id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Id")
                                .HasMaxLength(36)
                                .HasColumnType("character varying(36)")
                                .HasColumnName("id");

                            b1.Property<string>("AcceptanceThreshold")
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("acceptance_threshold");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("type");

                            b1.HasKey("qa_checkpoint_id", "Id");

                            b1.HasIndex("qa_checkpoint_id")
                                .HasDatabaseName("ix_qa_checkpoint_criteria_qa_checkpoint_id");

                            b1.ToTable("qa_checkpoint_criteria", "qa");

                            b1.WithOwner()
                                .HasForeignKey("qa_checkpoint_id");
                        });

                    b.Navigation("Criteria");
                });
#pragma warning restore 612, 618
        }
    }
}
