// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SpaceOS.Modules.Joinery.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Joinery.Infrastructure.Migrations;

[DbContext(typeof(JoineryDbContext))]
[Migration("20260410000001_J0002_V2_CuttingListSnapshot")]
partial class J0002_V2_CuttingListSnapshot
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Stub — full model snapshot in JoineryDbContextModelSnapshot.cs
    }
}
