// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using SpaceOS.Modules.Joinery.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Joinery.Infrastructure.Migrations;

[DbContext(typeof(JoineryDbContext))]
[Migration("20260409000001_Migration_0001_InitialSchema")]
partial class Migration_0001_InitialSchema
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
        // Stub — full model snapshot in JoineryDbContextModelSnapshot.cs
    }
}
