// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Joinery.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Joinery.Infrastructure.Migrations
{
    [DbContext(typeof(JoineryDbContext))]
    [Migration("20260419000001_AddGyartasilap")]
    partial class AddGyartasilap
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Gyartasilap entity — minimal representation for migration designer
            modelBuilder.Entity("SpaceOS.Modules.Joinery.Domain.Core.Gyartasilap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CuttingPlanId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JoineryOrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("LabelVariant")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<byte[]>("PdfContent")
                        .HasColumnType("bytea");

                    b.Property<string>("StorageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("CuttingPlanId", "CreatedAt")
                        .HasDatabaseName("IX_Gyartasilaps_PlanId_CreatedAt");

                    b.HasIndex("JoineryOrderId", "Status")
                        .HasDatabaseName("IX_Gyartasilaps_OrderId_Status");

                    b.ToTable("Gyartasilaps", "spaceos_joinery");
                });
#pragma warning restore 612, 618
        }
    }
}
