// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SpaceOS.Modules.Joinery.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Joinery.Infrastructure.Migrations;

[DbContext(typeof(JoineryDbContext))]
partial class JoineryDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        // Stub snapshot — generated by dotnet ef migrations add
    }
}
