/**
 * Project Status Updater (Track A)
 *
 * Generates and updates STATUS.md for projects based on TASKS.yaml state.
 *
 * Features:
 * - Progress tracking (% completion)
 * - Milestone status table
 * - Recent activity log
 * - Task breakdown by status
 * - Blocked tasks warning
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { TaskChain, Task, Milestone } from './projectDispatcher';
import { getBlockedTasks, getInProgressTasks } from './projectMatcher';
import { loadEpicGraphCached } from '../graph/epicsLoader';
import { generateMermaid } from '../graph/mermaidGenerator';
import { WorkflowGraph } from '../graph/types';

/**
 * Update project STATUS.md file
 *
 * @param projectPath Path to project directory
 * @param tasks Task chain from TASKS.yaml
 */
export async function updateProjectStatus(
  projectPath: string,
  tasks: TaskChain
): Promise<void> {
  const statusMd = generateStatusMarkdown(tasks);
  const statusPath = path.join(projectPath, 'STATUS.md');

  await fs.writeFile(statusPath, statusMd, 'utf-8');

  console.log(`[StatusUpdater] Updated ${statusPath}`);
}

/**
 * Generate STATUS.md markdown content
 *
 * @param tasks Task chain
 * @returns Markdown content
 */
export function generateStatusMarkdown(tasks: TaskChain): string {
  const stats = calculateStats(tasks);
  const milestoneTable = generateMilestoneTable(tasks);
  const taskBreakdown = generateTaskBreakdown(tasks);
  const blockedWarning = generateBlockedWarning(tasks);
  const recentActivity = generateRecentActivity(tasks);

  return `# ${tasks.project} — Status

**Generated:** ${new Date().toISOString()}
**Updated:** ${tasks.updated}

## Overall Progress

**${stats.completed}/${stats.total} tasks completed (${stats.progressPercent}%)**

${generateProgressBar(stats.progressPercent)}

${blockedWarning}

## Milestones

${milestoneTable}

## Task Breakdown

${taskBreakdown}

## Recent Activity

${recentActivity}

---

*Auto-generated by Project Automation System*
`;
}

/**
 * Calculate project statistics
 */
function calculateStats(tasks: TaskChain): {
  total: number;
  completed: number;
  inProgress: number;
  blocked: number;
  pending: number;
  progressPercent: number;
} {
  const allTasks = tasks.milestones.flatMap(m => m.tasks);

  const completed = allTasks.filter(t => t.status === 'done').length;
  const inProgress = allTasks.filter(t => t.status === 'in_progress').length;
  const blocked = allTasks.filter(t => t.status === 'blocked').length;
  const pending = allTasks.filter(t => t.status === 'pending').length;

  const total = allTasks.length;
  const progressPercent = total > 0 ? Math.round((completed / total) * 100) : 0;

  return {
    total,
    completed,
    inProgress,
    blocked,
    pending,
    progressPercent,
  };
}

/**
 * Generate ASCII progress bar
 */
function generateProgressBar(percent: number, width: number = 40): string {
  const filled = Math.round((percent / 100) * width);
  const empty = width - filled;

  const bar = '█'.repeat(filled) + '░'.repeat(empty);
  return `\`${bar}\` ${percent}%`;
}

/**
 * Generate milestone table
 */
function generateMilestoneTable(tasks: TaskChain): string {
  if (tasks.milestones.length === 0) {
    return '_No milestones defined_';
  }

  const rows = tasks.milestones.map(m => {
    const totalTasks = m.tasks.length;
    const doneTasks = m.tasks.filter(t => t.status === 'done').length;
    const percent = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;
    const statusEmoji = getStatusEmoji(m.status);

    return `| ${statusEmoji} ${m.name} | ${totalTasks} | ${doneTasks} | ${percent}% | ${m.status} |`;
  });

  return `| Milestone | Tasks | Done | % | Status |
|-----------|-------|------|---|--------|
${rows.join('\n')}`;
}

/**
 * Generate task breakdown section
 */
function generateTaskBreakdown(tasks: TaskChain): string {
  const allTasks = tasks.milestones.flatMap(m => m.tasks);

  const byStatus = {
    done: allTasks.filter(t => t.status === 'done'),
    in_progress: allTasks.filter(t => t.status === 'in_progress'),
    blocked: allTasks.filter(t => t.status === 'blocked'),
    pending: allTasks.filter(t => t.status === 'pending'),
  };

  const sections = [];

  // In Progress
  if (byStatus.in_progress.length > 0) {
    sections.push(`### 🔄 In Progress (${byStatus.in_progress.length})

${byStatus.in_progress.map(t => `- **${t.name}** (${t.terminal}) — ${t.msg_id || 'not started'}`).join('\n')}`);
  }

  // Blocked
  if (byStatus.blocked.length > 0) {
    sections.push(`### 🚫 Blocked (${byStatus.blocked.length})

${byStatus.blocked.map(t => {
  const blockers = t.blocked_by.join(', ');
  return `- **${t.name}** (${t.terminal}) — Blocked by: ${blockers}`;
}).join('\n')}`);
  }

  // Pending
  if (byStatus.pending.length > 0) {
    sections.push(`### ⏳ Pending (${byStatus.pending.length})

${byStatus.pending.map(t => {
  if (t.blocked_by.length > 0) {
    const blockers = t.blocked_by.join(', ');
    return `- **${t.name}** (${t.terminal}) — Waiting for: ${blockers}`;
  } else {
    return `- **${t.name}** (${t.terminal}) — Ready to start`;
  }
}).join('\n')}`);
  }

  // Done
  sections.push(`### ✅ Done (${byStatus.done.length})

${byStatus.done.length > 0
    ? byStatus.done.map(t => `- **${t.name}** (${t.completed_at || 'completed'})`).join('\n')
    : '_No tasks completed yet_'
  }`);

  return sections.join('\n\n');
}

/**
 * Generate blocked tasks warning
 */
function generateBlockedWarning(tasks: TaskChain): string {
  const blocked = getBlockedTasks(tasks);

  if (blocked.length === 0) {
    return '';
  }

  return `> ⚠️ **${blocked.length} task(s) BLOCKED** — Manual intervention may be required.\n`;
}

/**
 * Generate recent activity section
 */
function generateRecentActivity(tasks: TaskChain): string {
  const allTasks = tasks.milestones.flatMap(m => m.tasks);

  // Get tasks with completion timestamps
  const completedTasks = allTasks
    .filter(t => t.status === 'done' && t.completed_at)
    .sort((a, b) => {
      const dateA = new Date(a.completed_at!).getTime();
      const dateB = new Date(b.completed_at!).getTime();
      return dateB - dateA; // Most recent first
    })
    .slice(0, 10); // Last 10 activities

  if (completedTasks.length === 0) {
    return '_No activity yet_';
  }

  const activities = completedTasks.map(t => {
    const date = formatDate(t.completed_at!);
    return `- **${date}** — ✅ ${t.name} completed`;
  });

  return activities.join('\n');
}

/**
 * Get emoji for status
 */
function getStatusEmoji(status: string): string {
  switch (status) {
    case 'done':
      return '✅';
    case 'in_progress':
      return '🔄';
    case 'blocked':
      return '🚫';
    case 'pending':
      return '⏳';
    default:
      return '⚪';
  }
}

/**
 * Format ISO date to readable format
 */
function formatDate(isoDate: string): string {
  try {
    const date = new Date(isoDate);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffHours = Math.floor(diffMs / (1000 * 60 * 60));
    const diffDays = Math.floor(diffHours / 24);

    if (diffHours < 1) {
      return 'just now';
    } else if (diffHours < 24) {
      return `${diffHours}h ago`;
    } else if (diffDays < 7) {
      return `${diffDays}d ago`;
    } else {
      // Format as YYYY-MM-DD
      return isoDate.split('T')[0];
    }
  } catch {
    return isoDate;
  }
}

/**
 * Generate detailed status report (for logging/debugging)
 */
export function generateStatusReport(tasks: TaskChain): string {
  const stats = calculateStats(tasks);
  const blocked = getBlockedTasks(tasks);
  const inProgress = getInProgressTasks(tasks);

  return `
Project: ${tasks.project}
Progress: ${stats.completed}/${stats.total} (${stats.progressPercent}%)
In Progress: ${stats.inProgress}
Blocked: ${stats.blocked}
Pending: ${stats.pending}

Blocked Tasks: ${blocked.map(t => t.id).join(', ') || 'none'}
In Progress: ${inProgress.map(t => `${t.id} (${t.terminal})`).join(', ') || 'none'}
  `.trim();
}

/**
 * Generate epic status section for Codebase_Status.md (ADR-041 Phase 1 / TASK-004)
 *
 * Generates markdown table with epic-level completion tracking.
 *
 * @param includeMermaid Include Mermaid diagram
 * @returns Markdown content for epic section
 */
export async function generateEpicStatusSection(includeMermaid: boolean = false): Promise<string> {
  try {
    // Load epic graph
    const graph = await loadEpicGraphCached('docs/projects/EPICS.yaml');

    // Generate epic table
    const epicTable = generateEpicTable(graph);

    // Optional Mermaid diagram
    let mermaidSection = '';
    if (includeMermaid) {
      const mermaid = generateMermaid(graph);
      mermaidSection = `

### Dependency Graph

\`\`\`mermaid
${mermaid}
\`\`\`
`;
    }

    return `## Epic Dependency Status

**Overall Epic Completion:** ${graph.completion_percentage}%

${epicTable}${mermaidSection}

---
`;
  } catch (error: any) {
    console.warn('[StatusUpdater] Failed to generate epic status:', error.message);
    return `## Epic Dependency Status

⚠️ _Epic graph not available (${error.message})_

---
`;
  }
}

/**
 * Generate epic status table
 */
function generateEpicTable(graph: WorkflowGraph): string {
  if (graph.nodes.length === 0) {
    return '_No epics defined_';
  }

  const rows = graph.nodes.map(epic => {
    const statusEmoji = getStatusEmoji(epic.status);
    const project = epic.metadata.project as string;
    const dependsOn = epic.depends_on.length > 0 ? epic.depends_on.join(', ') : '—';

    return `| ${statusEmoji} ${epic.name} | ${project} | ${epic.status} | ${dependsOn} |`;
  });

  return `| Epic | Project | Status | Depends On |
|------|---------|--------|------------|
${rows.join('\n')}`;
}

/**
 * Update Codebase_Status.md with epic graph status (ADR-041 Phase 1 / TASK-004)
 *
 * Replaces the epic section in Codebase_Status.md with fresh data.
 *
 * @param statusPath Path to Codebase_Status.md (default: docs/Codebase_Status.md)
 * @param includeMermaid Include Mermaid diagram
 */
export async function updateCodebaseStatusWithEpics(
  statusPath: string = 'docs/Codebase_Status.md',
  includeMermaid: boolean = false
): Promise<void> {
  try {
    // Generate epic section
    const epicSection = await generateEpicStatusSection(includeMermaid);

    // Read existing STATUS.md
    let content: string;
    try {
      content = await fs.readFile(statusPath, 'utf-8');
    } catch (err: any) {
      if (err.code === 'ENOENT') {
        // File doesn't exist, create new
        content = `# SpaceOS Codebase Status

**Generated:** ${new Date().toISOString()}

${epicSection}
`;
        await fs.writeFile(statusPath, content, 'utf-8');
        console.log(`[StatusUpdater] Created ${statusPath} with epic status`);
        return;
      }
      throw err;
    }

    // Replace epic section (between "## Epic Dependency Status" and next "## " or "---")
    const epicSectionRegex = /## Epic Dependency Status[\s\S]*?(?=\n## |\n---\n|$)/;

    if (epicSectionRegex.test(content)) {
      // Replace existing epic section
      content = content.replace(epicSectionRegex, epicSection.trim());
    } else {
      // Append epic section before first "## " or at end
      const firstSectionMatch = content.match(/\n## /);
      if (firstSectionMatch) {
        const insertPos = firstSectionMatch.index!;
        content = content.slice(0, insertPos) + '\n' + epicSection + content.slice(insertPos);
      } else {
        content += '\n' + epicSection;
      }
    }

    // Write updated content
    await fs.writeFile(statusPath, content, 'utf-8');
    console.log(`[StatusUpdater] Updated ${statusPath} with epic status`);
  } catch (error: any) {
    console.error('[StatusUpdater] Failed to update Codebase_Status.md:', error);
    throw error;
  }
}

/**
 * Export status as JSON (for API endpoints)
 */
export function exportStatusJSON(tasks: TaskChain): {
  project: string;
  updated: string;
  stats: ReturnType<typeof calculateStats>;
  milestones: Array<{
    id: string;
    name: string;
    status: string;
    tasks: number;
    done: number;
    percent: number;
  }>;
  blocked: Array<{ id: string; name: string; terminal: string }>;
  inProgress: Array<{ id: string; name: string; terminal: string; msg_id?: string }>;
} {
  const stats = calculateStats(tasks);
  const blocked = getBlockedTasks(tasks);
  const inProgress = getInProgressTasks(tasks);

  return {
    project: tasks.project,
    updated: tasks.updated,
    stats,
    milestones: tasks.milestones.map(m => {
      const totalTasks = m.tasks.length;
      const doneTasks = m.tasks.filter(t => t.status === 'done').length;
      const percent = totalTasks > 0 ? Math.round((doneTasks / totalTasks) * 100) : 0;

      return {
        id: m.id,
        name: m.name,
        status: m.status,
        tasks: totalTasks,
        done: doneTasks,
        percent,
      };
    }),
    blocked: blocked.map(t => ({
      id: t.id,
      name: t.name,
      terminal: t.terminal,
    })),
    inProgress: inProgress.map(t => ({
      id: t.id,
      name: t.name,
      terminal: t.terminal,
      msg_id: t.msg_id,
    })),
  };
}
