using SpaceOS.Kernel.Domain.Primitives;

namespace SpaceOS.Modules.CRM.Domain.Events;

/// <summary>
/// LeadQualified domain event
/// Generated by SpaceOS Code Generator
/// </summary>
public record LeadQualifiedEvent(
    Guid LeadId,
    Guid TenantId,
    DateTime OccurredAt
) : IDomainEvent
{
    public DateTimeOffset OccurredOn { get; init; } = DateTimeOffset.UtcNow;

    public LeadQualifiedEvent(Guid leadId, Guid tenantId)
        : this(leadId, tenantId, DateTime.UtcNow) { }
}
