/**
 * Task Audit — Daily Report Generator
 *
 * Generates daily summary of:
 * - Tasks created via API
 * - Review outcomes (formal/content)
 * - Escalations
 * - Terminal activity
 *
 * Output formats:
 * - Markdown file (git tracked)
 * - Telegram notification
 * - JSON API response
 */

import * as fs from 'fs/promises';
import * as path from 'path';
import { getDailySummary, queryCreationLog, type DailySummary } from './taskCreation';
import { queryReviewLog } from '../pipeline/reviewLog';
import { telegram, log, SPACEOS_ROOT } from '../pipeline/common';

// ── Types ───────────────────────────────────────────────────────────────────

export interface DailyReport {
  date: string;
  generated_at: string;

  // Task creation stats
  tasks_created: {
    total: number;
    by_terminal: Record<string, number>;
    by_priority: Record<string, number>;
    by_creator: Record<string, number>;
  };

  // Review stats
  reviews: {
    total: number;
    approved: number;
    rejected: number;
    escalated: number;
    by_type: {
      formal: number;
      content: number;
      manual: number;
    };
  };

  // Highlights
  highlights: string[];
}

// ── Report Generation ───────────────────────────────────────────────────────

export async function generateDailyReport(date?: string): Promise<DailyReport> {
  const targetDate = date || new Date().toISOString().split('T')[0];

  // Get task creation summary
  const taskSummary = await getDailySummary(targetDate);

  // Get review log for the day
  let reviewStats = {
    total: 0,
    approved: 0,
    rejected: 0,
    escalated: 0,
    by_type: { formal: 0, content: 0, manual: 0 },
  };

  try {
    const reviews = await queryReviewLog({});
    const dayReviews = reviews.filter(r => r.timestamp.startsWith(targetDate));

    reviewStats.total = dayReviews.length;
    reviewStats.approved = dayReviews.filter(r => r.final_verdict === 'APPROVED').length;
    reviewStats.rejected = dayReviews.filter(r => r.final_verdict === 'REJECTED').length;
    reviewStats.escalated = dayReviews.filter(r => r.escalated).length;

    // Note: review_type tracking would need to be added to reviewLog
  } catch {
    // Review log may not exist yet
  }

  // Generate highlights
  const highlights: string[] = [];

  if (taskSummary.total_tasks > 0) {
    highlights.push(`${taskSummary.total_tasks} task(s) created via API`);
  }

  if (reviewStats.approved > 0) {
    const rate = Math.round((reviewStats.approved / reviewStats.total) * 100);
    highlights.push(`${reviewStats.approved}/${reviewStats.total} reviews approved (${rate}%)`);
  }

  if (reviewStats.escalated > 0) {
    highlights.push(`⚠️ ${reviewStats.escalated} escalation(s) to root`);
  }

  const topTerminal = Object.entries(taskSummary.by_terminal)
    .sort((a, b) => b[1] - a[1])[0];
  if (topTerminal) {
    highlights.push(`Most active terminal: ${topTerminal[0]} (${topTerminal[1]} tasks)`);
  }

  return {
    date: targetDate,
    generated_at: new Date().toISOString(),
    tasks_created: {
      total: taskSummary.total_tasks,
      by_terminal: taskSummary.by_terminal,
      by_priority: taskSummary.by_priority,
      by_creator: taskSummary.by_creator,
    },
    reviews: reviewStats,
    highlights,
  };
}

// ── Markdown Report ─────────────────────────────────────────────────────────

export async function saveDailyReportMarkdown(report: DailyReport): Promise<string> {
  const reportsDir = path.join(SPACEOS_ROOT, 'docs/reports/daily');
  await fs.mkdir(reportsDir, { recursive: true });

  const filename = `${report.date}.md`;
  const filepath = path.join(reportsDir, filename);

  const terminalTable = Object.entries(report.tasks_created.by_terminal)
    .map(([t, c]) => `| ${t} | ${c} |`)
    .join('\n');

  const priorityTable = Object.entries(report.tasks_created.by_priority)
    .map(([p, c]) => `| ${p} | ${c} |`)
    .join('\n');

  const content = `# Daily Report: ${report.date}

> Generated: ${report.generated_at}

## Summary

| Metric | Value |
|---|---|
| Tasks Created | ${report.tasks_created.total} |
| Reviews Total | ${report.reviews.total} |
| Reviews Approved | ${report.reviews.approved} |
| Reviews Rejected | ${report.reviews.rejected} |
| Escalations | ${report.reviews.escalated} |

## Highlights

${report.highlights.map(h => `- ${h}`).join('\n')}

## Tasks by Terminal

| Terminal | Count |
|---|---|
${terminalTable || '| (none) | 0 |'}

## Tasks by Priority

| Priority | Count |
|---|---|
${priorityTable || '| (none) | 0 |'}

## Reviews by Type

| Type | Count |
|---|---|
| Formal | ${report.reviews.by_type.formal} |
| Content | ${report.reviews.by_type.content} |
| Manual | ${report.reviews.by_type.manual} |

---

*This report was automatically generated by SpaceOS Task Audit system.*
`;

  await fs.writeFile(filepath, content, 'utf-8');
  await log(`[DailyReport] Saved to ${filepath}`);

  return filepath;
}

// ── Telegram Notification ───────────────────────────────────────────────────

export async function sendDailyReportTelegram(report: DailyReport): Promise<void> {
  const approvalRate = report.reviews.total > 0
    ? Math.round((report.reviews.approved / report.reviews.total) * 100)
    : 0;

  const message = `📊 *Daily Report: ${report.date}*

*Tasks Created:* ${report.tasks_created.total}
*Reviews:* ${report.reviews.approved}/${report.reviews.total} approved (${approvalRate}%)
${report.reviews.escalated > 0 ? `⚠️ *Escalations:* ${report.reviews.escalated}` : ''}

*Highlights:*
${report.highlights.map(h => `• ${h}`).join('\n')}`;

  await telegram(message);
}

// ── Main Generator ──────────────────────────────────────────────────────────

export async function generateAndPublishDailyReport(date?: string): Promise<{
  report: DailyReport;
  markdownPath: string;
}> {
  const report = await generateDailyReport(date);
  const markdownPath = await saveDailyReportMarkdown(report);
  await sendDailyReportTelegram(report);

  return { report, markdownPath };
}
