// SpaceOS.Infrastructure/Migrations/HashSink/HashSinkDbContextModelSnapshot.cs
// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Infrastructure.Migrations.HashSink;

[DbContext(typeof(HashSinkDbContext))]
partial class HashSinkDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("public")
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("SpaceOS.Infrastructure.Persistence.HashChainRecord", b =>
        {
            b.Property<long>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("bigint");

            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

            b.Property<Guid>("TenantId")
                .IsRequired()
                .HasColumnType("uuid");

            b.Property<Guid>("EventId")
                .IsRequired()
                .HasColumnType("uuid");

            b.Property<string>("StateHash")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("character varying(64)");

            b.Property<DateTimeOffset>("OccurredAt")
                .IsRequired()
                .HasColumnType("timestamp with time zone");

            b.Property<DateTimeOffset>("InsertedAt")
                .IsRequired()
                .HasColumnType("timestamp with time zone")
                .HasDefaultValueSql("now()");

            b.HasKey("Id");

            b.HasIndex("EventId")
                .IsUnique()
                .HasDatabaseName("IX_hash_chain_records_EventId");

            b.HasIndex("TenantId")
                .HasDatabaseName("IX_hash_chain_records_TenantId");

            b.HasIndex("OccurredAt")
                .HasDatabaseName("IX_hash_chain_records_OccurredAt");

            b.ToTable("hash_chain_records", "public");
        });
#pragma warning restore 612, 618
    }
}
