namespace SpaceOS.Modules.CRM.Domain.Aggregates;

/// <summary>
/// FSM states for Lead
/// Generated by SpaceOS Code Generator
/// </summary>
public enum LeadState
{
    New,
    Contacted,
    Qualified,
    Disqualified,
    ConvertedToOpportunity
}
