using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using SpaceOS.Modules.HR.Domain.Aggregates;

namespace SpaceOS.Modules.HR.Infrastructure.Data.Configuration;

/// <summary>
/// EF Core configuration for Employee aggregate.
/// </summary>
public class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
{
    public void Configure(EntityTypeBuilder<Employee> builder)
    {
        builder.ToTable("employees", "hr");

        builder.HasKey(e => e.Id);
        builder.Property(e => e.Id)
            .ValueGeneratedNever(); // Guid generated by aggregate

        builder.Property(e => e.FullName)
            .HasMaxLength(200)
            .IsRequired();

        builder.Property(e => e.Email)
            .HasMaxLength(200)
            .IsRequired();

        builder.Property(e => e.HireDate)
            .IsRequired();

        builder.Property(e => e.Status)
            .HasConversion<string>() // Enum → string
            .HasMaxLength(20)
            .IsRequired();

        builder.Property(e => e.Department)
            .HasMaxLength(100)
            .IsRequired();

        builder.Property(e => e.JobTitle)
            .HasMaxLength(100)
            .IsRequired();

        builder.Property(e => e.TenantId)
            .IsRequired();

        // Owned entity: EmployeeCompetency
        builder.OwnsMany(e => e.Competencies, comp =>
        {
            comp.ToTable("employee_competencies", "hr");
            comp.WithOwner().HasForeignKey(nameof(EmployeeCompetency.EmployeeId));
            comp.HasKey(nameof(EmployeeCompetency.Id));

            comp.Property(c => c.Id)
                .ValueGeneratedNever();

            comp.Property(c => c.CompetencyId)
                .IsRequired();

            comp.Property(c => c.CompetencyName)
                .HasMaxLength(200)
                .IsRequired();

            comp.Property(c => c.Level)
                .HasMaxLength(50)
                .IsRequired();

            comp.Property(c => c.ValidFrom)
                .IsRequired();

            comp.Property(c => c.ValidUntil)
                .IsRequired(false); // Nullable

            comp.HasIndex(c => c.CompetencyId);
        });

        // RLS support (multi-tenant)
        builder.HasQueryFilter(e => EF.Property<Guid>(e, nameof(Employee.TenantId)) == Guid.Empty);

        // Index for tenant queries
        builder.HasIndex(e => e.TenantId);
    }
}
