// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.CRM.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.CRM.Infrastructure.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260701000001_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("crm")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.CRM.Domain.Aggregates.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisqualificationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("disqualification_reason");

                    b.Property<Guid?>("OpportunityRef")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_ref");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_leads_assigned_to");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_leads_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_leads_tenant_id");

                    b.ToTable("leads", "crm");
                });

            modelBuilder.Entity("SpaceOS.Modules.CRM.Domain.Aggregates.Opportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AbandonmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("abandonment_reason");

                    b.Property<Guid>("AssignedTo")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_to");

                    b.Property<Guid?>("B2BPartnerRef")
                        .HasColumnType("uuid")
                        .HasColumnName("b2b_partner_ref");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("ExpectedCloseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expected_close_date");

                    b.Property<Guid?>("LeadRef")
                        .HasColumnType("uuid")
                        .HasColumnName("lead_ref");

                    b.Property<string>("LossReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("loss_reason");

                    b.Property<decimal>("Probability")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("probability");

                    b.Property<Guid?>("QuoteRef")
                        .HasColumnType("uuid")
                        .HasColumnName("quote_ref");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo")
                        .HasDatabaseName("ix_opportunities_assigned_to");

                    b.HasIndex("LeadRef")
                        .HasDatabaseName("ix_opportunities_lead_ref");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_opportunities_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_opportunities_tenant_id");

                    b.ToTable("opportunities", "crm");
                });
#pragma warning restore 612, 618
        }
    }
}
