using FluentAssertions;
using Xunit;
using SpaceOS.Modules.Contracts.Cutting.Events;
using SpaceOS.Modules.Contracts.Inventory.Enums;
using SpaceOS.Modules.Contracts.Inventory.Events;
using SpaceOS.Modules.Contracts.Procurement.Events;

namespace SpaceOS.Modules.Contracts.Tests.Shared;

public class ModuleEventTests
{
    [Fact]
    public void ModuleEvent_EventId_IsAutoGenerated()
    {
        var ev = new CuttingSheetReceived
        {
            TenantId = Guid.NewGuid(),
            OccurredAt = DateTimeOffset.UtcNow,
            SheetId = Guid.NewGuid(),
            SourceEntityId = Guid.NewGuid(),
            SourceModuleType = "Joinery",
        };

        ev.EventId.Should().NotBe(Guid.Empty);
    }

    [Fact]
    public void ModuleEvent_TwoInstances_HaveDifferentEventIds()
    {
        var tenantId = Guid.NewGuid();
        var now = DateTimeOffset.UtcNow;

        var ev1 = new CuttingSheetReceived
        {
            TenantId = tenantId,
            OccurredAt = now,
            SheetId = Guid.NewGuid(),
            SourceEntityId = Guid.NewGuid(),
            SourceModuleType = "Joinery",
        };

        var ev2 = new StockConsumed
        {
            TenantId = tenantId,
            OccurredAt = now,
            MaterialCode = "MDF18",
            Quantity = 3,
            ReferenceType = StockReferenceType.CuttingSheet,
            ReferenceId = Guid.NewGuid(),
        };

        ev1.EventId.Should().NotBe(ev2.EventId);
    }

    [Fact]
    public void ModuleEvent_OccurredAt_CanBeSet()
    {
        var expectedTime = new DateTimeOffset(2026, 4, 14, 10, 0, 0, TimeSpan.Zero);

        var ev = new PurchaseOrderCreated
        {
            TenantId = Guid.NewGuid(),
            OccurredAt = expectedTime,
            OrderId = Guid.NewGuid(),
            SupplierId = Guid.NewGuid(),
        };

        ev.OccurredAt.Should().Be(expectedTime);
    }

    [Fact]
    public void ModuleEvent_TenantId_CanBeSet()
    {
        var tenantId = Guid.NewGuid();

        var ev = new CuttingSheetReceived
        {
            TenantId = tenantId,
            OccurredAt = DateTimeOffset.UtcNow,
            SheetId = Guid.NewGuid(),
            SourceEntityId = Guid.NewGuid(),
            SourceModuleType = "Cabinet",
        };

        ev.TenantId.Should().Be(tenantId);
    }
}
