import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { DatabaseConnectionManager } from '../../metadata/DatabaseConnectionManager';
import { AgentDb } from '../../mcp/AgentDb';
import { createMcpServerRouter } from '../../mcp/mcpServer';
import { DocumentServer } from '../../mcp/DocumentServer';
import { SessionManager } from '../../mcp/SessionManager';
import { WorkflowStateTracker } from '../../metadata/WorkflowStateTracker';
import { Server } from 'http';
import express from 'express';
import request from 'supertest';
import { join } from 'path';
import { mkdirSync, rmSync } from 'fs';

// Helper to wait for setImmediate (AuditLogger uses this)
const waitForNextTick = () => new Promise(resolve => setImmediate(resolve));

describe('Integration: MCP Context Middleware & Audit Logger', () => {
    const testDir = join(__dirname, '../../test_data/McpContextTest');
    const dbPath = join(testDir, 'agentSystem.db');
    let connectionManager: DatabaseConnectionManager;
    let agentDb: AgentDb;
    let sessionManager: SessionManager;
    let workflowTracker: WorkflowStateTracker;
    let documentServer: DocumentServer;
    let app: express.Express;

    beforeEach(() => {
        mkdirSync(testDir, { recursive: true });

        connectionManager = new DatabaseConnectionManager(dbPath);
        agentDb = new AgentDb(connectionManager);
        agentDb.initSchema();

        sessionManager = new SessionManager(dbPath); // Fix: SessionManager expects dbPath
        workflowTracker = new WorkflowStateTracker(dbPath); // Fix: WorkflowStateTracker expects dbPath
        documentServer = new DocumentServer(testDir); // Fix: DocumentServer expects absolute path to database root

        app = express();
        app.use(express.json());

        const mcpRouter = createMcpServerRouter(
            documentServer,
            workflowTracker,
            undefined, // rbacFilter
            sessionManager,
            undefined, // resourceTracker
            agentDb,
            undefined // bootstrapService
        );

        app.use('/mcp', mcpRouter);

        // Seed required roles
        const db = connectionManager.getAdminPool();
        db.exec(`
            INSERT OR IGNORE INTO roles (domain, role_name, content)
            VALUES ('platform', 'sys_admin', 'Admin Content');
        `);

        // Seed some data
        const uniqueAgentId = `test_client_${Date.now()}_${Math.random()}`;
        const session = sessionManager.register('sys_admin', 'platform', uniqueAgentId);

        workflowTracker.createSession({
            sessionId: session.id,
            domain: 'platform',
            roleName: 'sys_admin',
            workflowId: 'agile-epic-lifecycle-v1',
            track: 'discovery'  // switch to discovery for tool testing
        });
    });

    afterEach(() => {
        agentDb.close();
        if (sessionManager && (sessionManager as any).db) (sessionManager as any).db.close();
        if (workflowTracker && (workflowTracker as any).db) (workflowTracker as any).db.close();
        rmSync(testDir, { recursive: true, force: true });
    });

    it('should handle search_audit_log via HTTP transport with minimal context', async () => {
        const sessions = sessionManager.listByStatus('started');
        expect(sessions.length).toBeGreaterThan(0);
        const activeSession = sessions[0].id;

        // 1. Initialize MCP Virtual Session via HTTP Transport
        const initPayload = {
            jsonrpc: "2.0",
            id: "init-1",
            method: "initialize",
            params: {
                protocolVersion: "2024-11-05",
                capabilities: {},
                clientInfo: { name: "test-client", "version": "1.0.0" }
            }
        };

        const initRes = await request(app)
            .post('/mcp/http')
            .set('Accept', 'application/json, text/event-stream')
            .send(initPayload);

        if (initRes.status !== 200) {
            console.log('HTTP Init 400 Response Body:', initRes.body || initRes.text);
        }
        expect(initRes.status).toBe(200);

        // We also need to send initialized notification to complete the handshake
        const initializedNotification = {
            jsonrpc: "2.0",
            method: "notifications/initialized"
        };

        // Wait, mcp-session-id is generated by the server. We should extract it.
        // Actually, we can just grab it from the headers of the initialized response or let the backend map it.
        // Or we don't need 'mcp-session-id' header here if we aren't using session tracking in transport,
        // but webStandardStreamableHttp enforces it if sessionIdGenerator is used.
        const transportSessionId = initRes.headers['mcp-session-id'];

        // call discovery tools using the same session
        const toolCalls = async () => {
            const argsBase = { session_id: activeSession };

            // request_context with phase
            const reqCtxPayload = {
                jsonrpc: "2.0",
                id: "tool-1",
                method: "callTool",
                params: {
                    toolName: "request_context",
                    arguments: { phase: "ideation" },
                    session_id: activeSession
                }
            };

            const resp1 = await request(app).post('/mcp/http').send(reqCtxPayload);
            expect(resp1.status).toBe(200);
            expect(resp1.body.result.success).toBe(true);
            expect(resp1.body.result.data.workflow_template).toContain('IDEATION');

            // reference_prior_discovery
            const refPayload = {
                jsonrpc: "2.0",
                id: "tool-2",
                method: "callTool",
                params: {
                    toolName: "reference_prior_discovery",
                    arguments: { search_text: "anything" },
                    session_id: activeSession
                }
            };
            const resp2 = await request(app).post('/mcp/http').send(refPayload);
            expect(resp2.status).toBe(200);
            expect(resp2.body.result.success).toBe(true);
            expect(resp2.body.result.data.total_found).toBe(0);

            // check_constraints via HTTP
            const checkPayload = {
                jsonrpc: "2.0",
                id: "tool-2b",
                method: "callTool",
                params: {
                    toolName: "check_constraints",
                    arguments: { idea_summary: "hi", constraint_set: "technical" },
                    session_id: activeSession
                }
            };
            const resp2b = await request(app).post('/mcp/http').send(checkPayload);
            expect(resp2b.status).toBe(200);
            expect(resp2b.body.result.success).toBe(true);
            expect(resp2b.body.result.data.go_no_go).toBe(true);

            // guidance
            const guidePayload = {
                jsonrpc: "2.0",
                id: "tool-2c",
                method: "callTool",
                params: {
                    toolName: "get_phase_guidance",
                    arguments: { current_phase: "ideation" },
                    session_id: activeSession
                }
            };
            const resp2c = await request(app).post('/mcp/http').send(guidePayload);
            expect(resp2c.status).toBe(200);
            expect(resp2c.body.result.success).toBe(true);
            expect(resp2c.body.result.data.next_phase).toBe('validation');

            // track a blocker via HTTP
            const blkPayload = {
                jsonrpc: "2.0",
                id: "tool-2d",
                method: "callTool",
                params: {
                    toolName: "track_blocker",
                    arguments: { blocker_text: "network down", severity: "HIGH", blocking_phase: "ideation" },
                    session_id: activeSession
                }
            };
            const blkRes = await request(app).post('/mcp/http').send(blkPayload);
            expect(blkRes.status).toBe(200);
            expect(blkRes.body.result.success).toBe(true);

            const queryBlk = {
                jsonrpc: "2.0",
                id: "tool-2e",
                method: "callTool",
                params: {
                    toolName: "query_blockers",
                    arguments: { phase: "ideation" },
                    session_id: activeSession
                }
            };
            const qRes = await request(app).post('/mcp/http').send(queryBlk);
            expect(qRes.status).toBe(200);
            expect(qRes.body.result.success).toBe(true);
            expect(qRes.body.result.data.length).toBeGreaterThan(0);

            // submit_discovery_outcome should work when session track is discovery
            const outcomePayload = {
                jsonrpc: "2.0",
                id: "tool-3",
                method: "callTool",
                params: {
                    toolName: "submit_discovery_outcome",
                    arguments: {
                        outcome_type: "LEARNING",
                        summary: "e2e test outcome",
                        blockers: [],
                        phase: "ideation",
                        artifacts: []
                    },
                    session_id: activeSession
                }
            };
            const resp3 = await request(app).post('/mcp/http').send(outcomePayload);
            expect(resp3.status).toBe(200);
            expect(resp3.body.result.success).toBe(true);
            expect(resp3.body.result.data.episode_id).toBeDefined();

            // attempt iteration-outcome before validation should fail
            const badOutcome = {
                jsonrpc: "2.0",
                id: "tool-4",
                method: "callTool",
                params: {
                    toolName: "submit_discovery_outcome",
                    arguments: {
                        outcome_type: "LEARNING",
                        summary: "early iteration",
                        blockers: [],
                        phase: "iteration",
                        artifacts: []
                    },
                    session_id: activeSession
                }
            };
            const badResp = await request(app).post('/mcp/http').send(badOutcome);
            expect(badResp.status).toBe(200);
            expect(badResp.body.result.success).toBe(false);
            expect(badResp.body.result.error.message).toContain('Cannot submit outcome');
        };

        // execute the tool calls immediately after handshake
        await toolCalls();

        if (transportSessionId) {
            await request(app)
                .post('/mcp/http')
                .set('Accept', 'application/json, text/event-stream')
                .set('mcp-session-id', transportSessionId)
                .send(initializedNotification);
        }

        // 2. Make HTTP MCP Call
        const mcpPayload = {
            jsonrpc: "2.0",
            id: "test-req-1",
            method: 'tools/call',
            params: {
                name: 'search_audit_log',
                arguments: {
                    // Just pass activeSession from DB as the tool arg to satisfy argument requirements if any
                    session_id: activeSession,
                    limit: 10
                }
            }
        };

        const res = await request(app)
            .post('/mcp/http')
            .set('Accept', 'application/json, text/event-stream')
            .set('mcp-session-id', transportSessionId || '') // Provide if required by transport
            .send(mcpPayload);

        if (res.status !== 200) {
            console.log('HTTP Tools Call 400 Response Body:', res.body || res.text);
        }
        expect(res.status).toBe(200);

        // Wait to make sure async audit logging has chance to run if it was called
        await waitForNextTick();

        // Query the database directly to check if audit log was written (mcpServer.ts handles tool registration)
        const entries = agentDb.searchAuditLog({});
        expect(Array.isArray(entries)).toBe(true);
    });

    it('should inject context and test searchAuditLog return structure', async () => {
        const entries = agentDb.searchAuditLog({ limit: 5 });
        expect(Array.isArray(entries)).toBe(true);
    });
});
