// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Abstractions.Infrastructure.Persistence;

#nullable disable

namespace SpaceOS.Modules.Abstractions.Infrastructure.Migrations
{
    [DbContext(typeof(AbstractionsDbContext))]
    partial class AbstractionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("spaceos_modules")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TradeType")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_ProductTemplates_TenantId");

                    b.HasIndex("TenantId", "TradeType")
                        .HasDatabaseName("IX_ProductTemplates_TenantId_TradeType")
                        .HasFilter("\"IsActive\" = true AND \"IsArchived\" = false");

                    b.HasIndex("TenantId", "Name", "Version")
                        .IsUnique();

                    b.ToTable("ProductTemplates", "spaceos_modules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.ComponentSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ComponentType")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DefaultMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("DefaultThickness")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ProductTemplateId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("SemanticRole")
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductTemplateId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_ComponentSlots_TemplateId");

                    b.ToTable("ComponentSlots", "spaceos_modules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.GeometryAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileFormat")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileReference")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("SkeletonJson")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SlotInstanceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SpatialElementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SlotInstanceId")
                        .HasDatabaseName("IX_GeometryAttachments_SlotInstanceId");

                    b.HasIndex("SpatialElementId")
                        .HasDatabaseName("IX_GeometryAttachments_SpatialElementId")
                        .HasFilter("\"SpatialElementId\" IS NOT NULL");

                    b.ToTable("GeometryAttachments", "spaceos_modules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.SlotConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Angle")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<Guid>("ChildSlotId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DrillDepth")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("DrillDiameter")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("GrooveDepth")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal?>("GrooveWidth")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("JointNote")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("JointType")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("MachiningOp")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("MultiplierCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("Operand")
                        .HasColumnType("decimal(8,3)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid>("ParentSlotId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProcessPhase")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("ProductTemplateId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Radius")
                        .HasColumnType("decimal(6,2)");

                    b.Property<Guid?>("SecondaryParentSlotId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChildSlotId")
                        .HasDatabaseName("IX_SlotConnections_ChildSlotId");

                    b.HasIndex("ParentSlotId")
                        .HasDatabaseName("IX_SlotConnections_ParentSlotId");

                    b.HasIndex("ProductTemplateId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_SlotConnections_TemplateId");

                    b.HasIndex("TemplateId", "ParentSlotId", "ChildSlotId", "Axis")
                        .IsUnique();

                    b.ToTable("SlotConnections", "spaceos_modules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.TemplateParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("ProductTemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(10,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductTemplateId");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("IX_TemplateParameters_TemplateId");

                    b.HasIndex("TemplateId", "Key")
                        .IsUnique();

                    b.ToTable("TemplateParameters", "spaceos_modules");
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.ComponentSlot", b =>
                {
                    b.HasOne("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", null)
                        .WithMany("Slots")
                        .HasForeignKey("ProductTemplateId");

                    b.HasOne("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.SlotConnection", b =>
                {
                    b.HasOne("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", null)
                        .WithMany("Connections")
                        .HasForeignKey("ProductTemplateId");

                    b.HasOne("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Entities.TemplateParameter", b =>
                {
                    b.HasOne("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", null)
                        .WithMany("Parameters")
                        .HasForeignKey("ProductTemplateId");

                    b.HasOne("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", null)
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpaceOS.Modules.Abstractions.Domain.Aggregates.ProductTemplate", b =>
                {
                    b.Navigation("Connections");

                    b.Navigation("Parameters");

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
