// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SpaceOS.Modules.Ehs.Infrastructure.Data;

#nullable disable

namespace SpaceOS.Modules.Ehs.Infrastructure.Migrations
{
    [DbContext(typeof(EhsDbContext))]
    partial class EhsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("IncidentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("incident_date");

                    b.Property<string>("IncidentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("incident_type");

                    b.Property<DateTimeOffset?>("InvestigatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("investigated_at");

                    b.Property<Guid?>("InvestigatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("investigated_by");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<Guid>("ReportedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reported_by");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("IncidentId");

                    b.HasIndex("IncidentDate")
                        .HasDatabaseName("ix_incidents_incident_date");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_incidents_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_incidents_tenant_id");

                    b.ToTable("incidents", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.RiskAssessmentAggregate.RiskAssessment", b =>
                {
                    b.Property<Guid>("RiskAssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("risk_assessment_id");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at");

                    b.Property<Guid>("AssessedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assessed_by");

                    b.Property<string>("HazardDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("hazard_description");

                    b.Property<string>("Likelihood")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("likelihood");

                    b.Property<DateTimeOffset>("ReviewDueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("review_due_date");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("risk_level");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer")
                        .HasColumnName("risk_score");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("RiskAssessmentId");

                    b.HasIndex("ReviewDueDate")
                        .HasDatabaseName("ix_risk_assessments_review_due_date");

                    b.HasIndex("RiskLevel")
                        .HasDatabaseName("ix_risk_assessments_risk_level");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_risk_assessments_status");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_risk_assessments_tenant_id");

                    b.ToTable("risk_assessments", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.TrainingRecordAggregate.TrainingRecord", b =>
                {
                    b.Property<Guid>("TrainingRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("training_record_id");

                    b.Property<string>("CertificateNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("certificate_number");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("issued_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TrainingType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("training_type");

                    b.HasKey("TrainingRecordId");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_training_records_employee_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_training_records_expires_at");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_training_records_tenant_id");

                    b.HasIndex("TrainingType")
                        .HasDatabaseName("ix_training_records_training_type");

                    b.ToTable("training_records", "ehs");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.Incident", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.CorrectiveAction", "CorrectiveActions", b1 =>
                        {
                            b1.Property<Guid>("incident_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CorrectiveActionId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("corrective_action_id");

                            b1.Property<Guid>("AssignedTo")
                                .HasColumnType("uuid")
                                .HasColumnName("assigned_to");

                            b1.Property<DateTimeOffset?>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("description");

                            b1.Property<DateTimeOffset>("DueDate")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("due_date");

                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_id");

                            b1.HasKey("incident_id", "CorrectiveActionId");

                            b1.HasIndex("incident_id")
                                .HasDatabaseName("ix_incident_corrective_actions_incident_id");

                            b1.ToTable("incident_corrective_actions", "ehs", t =>
                                {
                                    t.Property("incident_id")
                                        .HasColumnName("incident_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("incident_id");
                        });

                    b.OwnsOne("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.IncidentInvestigation", "Investigation", b1 =>
                        {
                            b1.Property<Guid>("incident_id")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset>("CompletedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("completed_at");

                            b1.Property<string>("Findings")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("findings");

                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_id");

                            b1.Property<Guid>("IncidentInvestigationId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_investigation_id");

                            b1.Property<Guid>("InvestigatedBy")
                                .HasColumnType("uuid")
                                .HasColumnName("investigated_by");

                            b1.Property<string>("Recommendations")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("recommendations");

                            b1.Property<string>("RootCause")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("root_cause");

                            b1.HasKey("incident_id");

                            b1.HasIndex("incident_id")
                                .HasDatabaseName("ix_incident_investigations_incident_id");

                            b1.ToTable("incident_investigations", "ehs", t =>
                                {
                                    t.Property("incident_id")
                                        .HasColumnName("incident_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("incident_id");
                        });

                    b.OwnsMany("SpaceOS.Modules.Ehs.Domain.Aggregates.IncidentAggregate.IncidentWitness", "Witnesses", b1 =>
                        {
                            b1.Property<Guid>("incident_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("IncidentWitnessId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("incident_witness_id");

                            b1.Property<Guid>("EmployeeId")
                                .HasColumnType("uuid")
                                .HasColumnName("employee_id");

                            b1.Property<Guid>("IncidentId")
                                .HasColumnType("uuid")
                                .HasColumnName("incident_id");

                            b1.Property<DateTimeOffset>("RecordedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("recorded_at");

                            b1.Property<string>("Statement")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("statement");

                            b1.HasKey("incident_id", "IncidentWitnessId");

                            b1.HasIndex("incident_id")
                                .HasDatabaseName("ix_incident_witnesses_incident_id");

                            b1.ToTable("incident_witnesses", "ehs", t =>
                                {
                                    t.Property("incident_id")
                                        .HasColumnName("incident_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("incident_id");
                        });

                    b.Navigation("CorrectiveActions");

                    b.Navigation("Investigation");

                    b.Navigation("Witnesses");
                });

            modelBuilder.Entity("SpaceOS.Modules.Ehs.Domain.Aggregates.RiskAssessmentAggregate.RiskAssessment", b =>
                {
                    b.OwnsMany("SpaceOS.Modules.Ehs.Domain.Aggregates.RiskAssessmentAggregate.RiskControl", "Controls", b1 =>
                        {
                            b1.Property<Guid>("risk_assessment_id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("RiskControlId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("risk_control_id");

                            b1.Property<string>("ControlMeasure")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("control_measure");

                            b1.Property<DateTimeOffset>("ImplementedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("implemented_at");

                            b1.Property<string>("ResponsiblePerson")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("responsible_person");

                            b1.Property<Guid>("RiskAssessmentId")
                                .HasColumnType("uuid")
                                .HasColumnName("risk_assessment_id");

                            b1.Property<DateTimeOffset?>("VerifiedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("verified_at");

                            b1.HasKey("risk_assessment_id", "RiskControlId");

                            b1.HasIndex("risk_assessment_id")
                                .HasDatabaseName("ix_risk_controls_risk_assessment_id");

                            b1.ToTable("risk_controls", "ehs", t =>
                                {
                                    t.Property("risk_assessment_id")
                                        .HasColumnName("risk_assessment_id1");
                                });

                            b1.WithOwner()
                                .HasForeignKey("risk_assessment_id");
                        });

                    b.Navigation("Controls");
                });
#pragma warning restore 612, 618
        }
    }
}
