# SpaceOS Telegram Bot konfiguráció
# Ez a fájl NINCS verziókövetve (.gitignore-ban van)

TELEGRAM_TOKEN="8782553868:AAGe9OmkM8tlWZToeoWMLvT8pAUqcPr5O2Y"
TELEGRAM_BOT="@SpaceOS_dispatcher_bot"

# Az első /start után automatikusan kitöltődik:
TELEGRAM_CHAT_ID="8426048796"
