// Identity.Infrastructure/Persistence/Migrations/IdentityDbContextModelSnapshot.cs

// <auto-generated />
using System;
using Identity.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Identity.Infrastructure.Persistence.Migrations;

[DbContext(typeof(IdentityDbContext))]
partial class IdentityDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasDefaultSchema("identity")
            .HasAnnotation("ProductVersion", "8.0.13")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        modelBuilder.Entity("Identity.Application.Common.KcSyncOutboxEntry", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id");
            b.Property<int>("AttemptCount").HasDefaultValue(0).HasColumnName("attempt_count");
            b.Property<DateTimeOffset>("CreatedAt").HasColumnName("created_at");
            b.Property<DateTimeOffset?>("LastAttemptAt").HasColumnName("last_attempt_at").IsRequired(false);
            b.Property<string>("Operation").HasMaxLength(30).HasColumnName("operation").IsRequired();
            b.Property<string>("Payload").HasColumnName("payload").IsRequired(false);
            b.Property<DateTimeOffset?>("ProcessedAt").HasColumnName("processed_at").IsRequired(false);
            b.Property<Guid>("TenantId").HasColumnName("tenant_id");
            b.Property<Guid>("UserId").HasColumnName("user_id");
            b.HasKey("Id");
            b.ToTable("kc_sync_outbox", "identity");
        });

        modelBuilder.Entity("Identity.Infrastructure.Persistence.Configurations.AuditLogEntry", b =>
        {
            b.Property<Guid>("Id").HasColumnName("id");
            b.Property<string>("Action").HasMaxLength(100).HasColumnName("action").IsRequired();
            b.Property<DateTimeOffset>("OccurredAt").HasColumnName("occurred_at");
            b.Property<string>("Payload").HasColumnName("payload").IsRequired(false);
            b.Property<string>("TargetType").HasMaxLength(50).HasColumnName("target_type").IsRequired(false);
            b.Property<Guid?>("TargetId").HasColumnName("target_id").IsRequired(false);
            b.Property<Guid>("TenantId").HasColumnName("tenant_id");
            b.Property<Guid?>("UserId").HasColumnName("user_id").IsRequired(false);
            b.HasKey("Id");
            b.ToTable("audit_log", "identity");
        });
#pragma warning restore 612, 618
    }
}
