#!/bin/bash
#
# generate-module.sh — SpaceOS .NET Module Generator
# Part of SpaceOS Code Generator Toolchain (ADR-050 Phase 2)
#
# Usage:
#   ./generate-module.sh <name> [options]
#
# Options:
#   --aggregate <name>     Aggregate root name (default: same as module)
#   --states <s1,s2,...>   FSM states (comma-separated)
#   --events <e1,e2,...>   Domain events (comma-separated)
#   --with-api             Generate API endpoints
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPACEOS_ROOT="/opt/spaceos"
MODULES_DIR="$SPACEOS_ROOT/backend/spaceos-modules"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Default values
MODULE_NAME=""
AGGREGATE_NAME=""
STATES=""
EVENTS=""
WITH_API=false

parse_args() {
    if [ $# -lt 1 ]; then
        show_usage
        exit 1
    fi

    MODULE_NAME="$1"
    AGGREGATE_NAME="$1"  # Default aggregate = module name
    shift

    while [ $# -gt 0 ]; do
        case "$1" in
            --aggregate)
                AGGREGATE_NAME="$2"
                shift 2
                ;;
            --states)
                STATES="$2"
                shift 2
                ;;
            --events)
                EVENTS="$2"
                shift 2
                ;;
            --with-api)
                WITH_API=true
                shift
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
}

generate_module() {
    local module_dir="$MODULES_DIR/spaceos-modules-${MODULE_NAME,,}"
    local namespace="SpaceOS.Modules.${MODULE_NAME}"

    log_info "Generating module: $MODULE_NAME"
    log_info "Aggregate: $AGGREGATE_NAME"
    log_info "Output: $module_dir"

    # Create directory structure
    mkdir -p "$module_dir/src/Domain/Aggregates"
    mkdir -p "$module_dir/src/Domain/Events"
    mkdir -p "$module_dir/src/Domain/ValueObjects"
    mkdir -p "$module_dir/src/Application/Commands"
    mkdir -p "$module_dir/src/Application/Queries"
    mkdir -p "$module_dir/src/Infrastructure/Persistence"
    mkdir -p "$module_dir/tests"

    # Generate .csproj
    cat > "$module_dir/src/$namespace.csproj" << EOF
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>$namespace</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../spaceos-kernel/SpaceOS.Kernel.Contracts/SpaceOS.Kernel.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.0" />
    <PackageReference Include="FluentValidation" Version="11.9.0" />
  </ItemGroup>
</Project>
EOF

    log_success "Created: $namespace.csproj"

    # Generate Aggregate
    generate_aggregate "$module_dir" "$namespace"

    # Generate FSM States if provided
    if [ -n "$STATES" ]; then
        generate_states "$module_dir" "$namespace"
    fi

    # Generate Events if provided
    if [ -n "$EVENTS" ]; then
        generate_events "$module_dir" "$namespace"
    fi

    # Generate API endpoints if requested
    if [ "$WITH_API" = true ]; then
        generate_api "$module_dir" "$namespace"
    fi

    # Generate test project
    generate_tests "$module_dir" "$namespace"

    echo ""
    log_success "Module $MODULE_NAME generated successfully!"
    echo ""
    log_info "Next steps:"
    echo "  1. cd $module_dir"
    echo "  2. dotnet build"
    echo "  3. Register module in Kernel DI"
}

generate_aggregate() {
    local module_dir="$1"
    local namespace="$2"

    cat > "$module_dir/src/Domain/Aggregates/${AGGREGATE_NAME}.cs" << EOF
using SpaceOS.Kernel.Contracts.Domain;

namespace ${namespace}.Domain.Aggregates;

/// <summary>
/// $AGGREGATE_NAME aggregate root
/// Generated by SpaceOS Code Generator
/// </summary>
public class $AGGREGATE_NAME : AggregateRoot<Guid>
{
    public string Name { get; private set; } = string.Empty;
    public ${AGGREGATE_NAME}State State { get; private set; } = ${AGGREGATE_NAME}State.Draft;
    public Guid TenantId { get; private set; }
    public DateTime CreatedAt { get; private set; }
    public DateTime? UpdatedAt { get; private set; }

    private $AGGREGATE_NAME() { } // EF Core

    public static $AGGREGATE_NAME Create(Guid tenantId, string name)
    {
        var entity = new $AGGREGATE_NAME
        {
            Id = Guid.NewGuid(),
            TenantId = tenantId,
            Name = name,
            State = ${AGGREGATE_NAME}State.Draft,
            CreatedAt = DateTime.UtcNow
        };

        entity.AddDomainEvent(new ${AGGREGATE_NAME}CreatedEvent(entity.Id, tenantId, name));
        return entity;
    }

    public void UpdateName(string name)
    {
        Name = name;
        UpdatedAt = DateTime.UtcNow;
        AddDomainEvent(new ${AGGREGATE_NAME}UpdatedEvent(Id, name));
    }
}
EOF

    log_success "Created: Domain/Aggregates/${AGGREGATE_NAME}.cs"
}

generate_states() {
    local module_dir="$1"
    local namespace="$2"

    # Parse states
    IFS=',' read -ra STATE_ARRAY <<< "$STATES"

    cat > "$module_dir/src/Domain/Aggregates/${AGGREGATE_NAME}State.cs" << EOF
namespace ${namespace}.Domain.Aggregates;

/// <summary>
/// FSM states for $AGGREGATE_NAME
/// Generated by SpaceOS Code Generator
/// </summary>
public enum ${AGGREGATE_NAME}State
{
EOF

    for i in "${!STATE_ARRAY[@]}"; do
        local state="${STATE_ARRAY[$i]}"
        state="$(echo "$state" | xargs)"  # trim whitespace
        if [ $i -eq $((${#STATE_ARRAY[@]} - 1)) ]; then
            echo "    $state" >> "$module_dir/src/Domain/Aggregates/${AGGREGATE_NAME}State.cs"
        else
            echo "    $state," >> "$module_dir/src/Domain/Aggregates/${AGGREGATE_NAME}State.cs"
        fi
    done

    echo "}" >> "$module_dir/src/Domain/Aggregates/${AGGREGATE_NAME}State.cs"

    log_success "Created: Domain/Aggregates/${AGGREGATE_NAME}State.cs"
}

generate_events() {
    local module_dir="$1"
    local namespace="$2"

    # Parse events
    IFS=',' read -ra EVENT_ARRAY <<< "$EVENTS"

    for event in "${EVENT_ARRAY[@]}"; do
        event="$(echo "$event" | xargs)"  # trim whitespace

        cat > "$module_dir/src/Domain/Events/${event}Event.cs" << EOF
using SpaceOS.Kernel.Contracts.Domain;

namespace ${namespace}.Domain.Events;

/// <summary>
/// $event domain event
/// Generated by SpaceOS Code Generator
/// </summary>
public record ${event}Event(
    Guid ${AGGREGATE_NAME}Id,
    Guid TenantId,
    DateTime OccurredAt
) : IDomainEvent
{
    public ${event}Event(Guid ${AGGREGATE_NAME,,}Id, Guid tenantId)
        : this(${AGGREGATE_NAME,,}Id, tenantId, DateTime.UtcNow) { }
}
EOF

        log_success "Created: Domain/Events/${event}Event.cs"
    done

    # Generate base events (Created, Updated)
    cat > "$module_dir/src/Domain/Events/${AGGREGATE_NAME}CreatedEvent.cs" << EOF
using SpaceOS.Kernel.Contracts.Domain;

namespace ${namespace}.Domain.Events;

public record ${AGGREGATE_NAME}CreatedEvent(
    Guid ${AGGREGATE_NAME}Id,
    Guid TenantId,
    string Name
) : IDomainEvent;
EOF

    cat > "$module_dir/src/Domain/Events/${AGGREGATE_NAME}UpdatedEvent.cs" << EOF
using SpaceOS.Kernel.Contracts.Domain;

namespace ${namespace}.Domain.Events;

public record ${AGGREGATE_NAME}UpdatedEvent(
    Guid ${AGGREGATE_NAME}Id,
    string Name
) : IDomainEvent;
EOF

    log_success "Created: Domain/Events/${AGGREGATE_NAME}CreatedEvent.cs"
    log_success "Created: Domain/Events/${AGGREGATE_NAME}UpdatedEvent.cs"
}

generate_api() {
    local module_dir="$1"
    local namespace="$2"

    mkdir -p "$module_dir/src/Api"

    cat > "$module_dir/src/Api/${AGGREGATE_NAME}Endpoints.cs" << EOF
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Routing;

namespace ${namespace}.Api;

/// <summary>
/// API endpoints for $AGGREGATE_NAME
/// Generated by SpaceOS Code Generator
/// </summary>
public static class ${AGGREGATE_NAME}Endpoints
{
    public static IEndpointRouteBuilder Map${AGGREGATE_NAME}Endpoints(this IEndpointRouteBuilder app)
    {
        var group = app.MapGroup("/api/${AGGREGATE_NAME,,}s")
            .WithTags("${AGGREGATE_NAME}s")
            .RequireAuthorization();

        group.MapGet("/", GetAll)
            .WithSummary("Get all ${AGGREGATE_NAME}s")
            .Produces<List<${AGGREGATE_NAME}Dto>>();

        group.MapGet("/{id:guid}", GetById)
            .WithSummary("Get ${AGGREGATE_NAME} by ID")
            .Produces<${AGGREGATE_NAME}Dto>()
            .ProducesProblem(404);

        group.MapPost("/", Create)
            .WithSummary("Create new ${AGGREGATE_NAME}")
            .Produces<Guid>(201)
            .ProducesValidationProblem();

        group.MapPut("/{id:guid}", Update)
            .WithSummary("Update ${AGGREGATE_NAME}")
            .Produces(204)
            .ProducesProblem(404);

        group.MapDelete("/{id:guid}", Delete)
            .WithSummary("Delete ${AGGREGATE_NAME}")
            .Produces(204)
            .ProducesProblem(404);

        return app;
    }

    private static async Task<IResult> GetAll() => Results.Ok(new List<${AGGREGATE_NAME}Dto>());
    private static async Task<IResult> GetById(Guid id) => Results.Ok(new ${AGGREGATE_NAME}Dto());
    private static async Task<IResult> Create() => Results.Created("/", Guid.NewGuid());
    private static async Task<IResult> Update(Guid id) => Results.NoContent();
    private static async Task<IResult> Delete(Guid id) => Results.NoContent();
}

public record ${AGGREGATE_NAME}Dto(
    Guid Id = default,
    string Name = "",
    string State = ""
);
EOF

    log_success "Created: Api/${AGGREGATE_NAME}Endpoints.cs"
}

generate_tests() {
    local module_dir="$1"
    local namespace="$2"

    cat > "$module_dir/tests/${namespace}.Tests.csproj" << EOF
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../src/${namespace}.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.11.0" />
    <PackageReference Include="xunit" Version="2.9.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>
</Project>
EOF

    cat > "$module_dir/tests/${AGGREGATE_NAME}Tests.cs" << EOF
using FluentAssertions;
using ${namespace}.Domain.Aggregates;
using Xunit;

namespace ${namespace}.Tests;

public class ${AGGREGATE_NAME}Tests
{
    [Fact]
    public void Create_Should_Initialize_With_Draft_State()
    {
        // Arrange
        var tenantId = Guid.NewGuid();
        var name = "Test ${AGGREGATE_NAME}";

        // Act
        var entity = ${AGGREGATE_NAME}.Create(tenantId, name);

        // Assert
        entity.Id.Should().NotBeEmpty();
        entity.TenantId.Should().Be(tenantId);
        entity.Name.Should().Be(name);
        entity.State.Should().Be(${AGGREGATE_NAME}State.Draft);
    }

    [Fact]
    public void UpdateName_Should_Change_Name()
    {
        // Arrange
        var entity = ${AGGREGATE_NAME}.Create(Guid.NewGuid(), "Original");

        // Act
        entity.UpdateName("Updated");

        // Assert
        entity.Name.Should().Be("Updated");
        entity.UpdatedAt.Should().NotBeNull();
    }
}
EOF

    log_success "Created: tests/${namespace}.Tests.csproj"
    log_success "Created: tests/${AGGREGATE_NAME}Tests.cs"
}

show_usage() {
    echo "Usage: $0 <name> [options]"
    echo ""
    echo "Arguments:"
    echo "  name                       Module name (PascalCase)"
    echo ""
    echo "Options:"
    echo "  --aggregate <name>         Aggregate root name (default: same as module)"
    echo "  --states <s1,s2,...>       FSM states (comma-separated)"
    echo "  --events <e1,e2,...>       Domain events (comma-separated)"
    echo "  --with-api                 Generate API endpoints"
    echo ""
    echo "Examples:"
    echo "  $0 Pricing"
    echo "  $0 Pricing --aggregate Quote --states Draft,Submitted,Approved,Rejected"
    echo "  $0 Cutting --states Pending,InProgress,Completed --with-api"
}

main() {
    parse_args "$@"

    # Validate module name (PascalCase)
    if [[ ! "$MODULE_NAME" =~ ^[A-Z][a-zA-Z0-9]*$ ]]; then
        log_error "Module name must be PascalCase (e.g., Pricing)"
        exit 1
    fi

    generate_module
}

main "$@"
