#!/bin/bash
#
# generate-component.sh — SpaceOS React Component Generator
# Part of SpaceOS Code Generator Toolchain (ADR-050 Phase 2)
#
# Usage:
#   ./generate-component.sh <name> [options]
#
# Options:
#   --category <feature|ui|layout>  Component category (default: feature)
#   --with-test                     Generate test file
#   --with-story                    Generate Storybook story
#   --path <dir>                    Custom output path
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPACEOS_ROOT="/opt/spaceos"
PORTAL_DIR="$SPACEOS_ROOT/datahaven-web/client"
TEMPLATES_DIR="$SCRIPT_DIR/templates"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Default values
COMPONENT_NAME=""
CATEGORY="feature"
WITH_TEST=false
WITH_STORY=false
CUSTOM_PATH=""

parse_args() {
    if [ $# -lt 1 ]; then
        show_usage
        exit 1
    fi

    COMPONENT_NAME="$1"
    shift

    while [ $# -gt 0 ]; do
        case "$1" in
            --category)
                CATEGORY="$2"
                shift 2
                ;;
            --with-test)
                WITH_TEST=true
                shift
                ;;
            --with-story)
                WITH_STORY=true
                shift
                ;;
            --path)
                CUSTOM_PATH="$2"
                shift 2
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
}

get_output_dir() {
    if [ -n "$CUSTOM_PATH" ]; then
        echo "$PORTAL_DIR/src/$CUSTOM_PATH"
    else
        case "$CATEGORY" in
            feature) echo "$PORTAL_DIR/src/components/features" ;;
            ui) echo "$PORTAL_DIR/src/components/ui" ;;
            layout) echo "$PORTAL_DIR/src/components/layout" ;;
            *) echo "$PORTAL_DIR/src/components" ;;
        esac
    fi
}

generate_component() {
    local output_dir
    output_dir="$(get_output_dir)/$COMPONENT_NAME"

    log_info "Generating component: $COMPONENT_NAME"
    log_info "Category: $CATEGORY"
    log_info "Output: $output_dir"

    mkdir -p "$output_dir"

    # Main component file
    cat > "$output_dir/$COMPONENT_NAME.tsx" << EOF
import React from 'react';
import styles from './$COMPONENT_NAME.module.css';

export interface ${COMPONENT_NAME}Props {
  className?: string;
  children?: React.ReactNode;
}

/**
 * $COMPONENT_NAME component
 * Category: $CATEGORY
 * Generated by SpaceOS Code Generator
 */
export const $COMPONENT_NAME: React.FC<${COMPONENT_NAME}Props> = ({
  className,
  children,
}) => {
  return (
    <div className={\`\${styles.container} \${className ?? ''}\`}>
      {children}
    </div>
  );
};

export default $COMPONENT_NAME;
EOF

    log_success "Created: $output_dir/$COMPONENT_NAME.tsx"

    # CSS Module
    cat > "$output_dir/$COMPONENT_NAME.module.css" << EOF
/* $COMPONENT_NAME styles */
/* Generated by SpaceOS Code Generator */

.container {
  /* Add your styles here */
}
EOF

    log_success "Created: $output_dir/$COMPONENT_NAME.module.css"

    # Index file
    cat > "$output_dir/index.ts" << EOF
export { $COMPONENT_NAME, type ${COMPONENT_NAME}Props } from './$COMPONENT_NAME';
export { default } from './$COMPONENT_NAME';
EOF

    log_success "Created: $output_dir/index.ts"

    # Optional: Test file
    if [ "$WITH_TEST" = true ]; then
        cat > "$output_dir/$COMPONENT_NAME.test.tsx" << EOF
import { render, screen } from '@testing-library/react';
import { describe, it, expect } from 'vitest';
import { $COMPONENT_NAME } from './$COMPONENT_NAME';

describe('$COMPONENT_NAME', () => {
  it('renders without crashing', () => {
    render(<$COMPONENT_NAME />);
  });

  it('renders children', () => {
    render(<$COMPONENT_NAME>Test Content</$COMPONENT_NAME>);
    expect(screen.getByText('Test Content')).toBeInTheDocument();
  });

  it('applies custom className', () => {
    const { container } = render(<$COMPONENT_NAME className="custom" />);
    expect(container.firstChild).toHaveClass('custom');
  });
});
EOF

        log_success "Created: $output_dir/$COMPONENT_NAME.test.tsx"
    fi

    # Optional: Storybook story
    if [ "$WITH_STORY" = true ]; then
        cat > "$output_dir/$COMPONENT_NAME.stories.tsx" << EOF
import type { Meta, StoryObj } from '@storybook/react';
import { $COMPONENT_NAME } from './$COMPONENT_NAME';

const meta: Meta<typeof $COMPONENT_NAME> = {
  title: 'Components/$CATEGORY/$COMPONENT_NAME',
  component: $COMPONENT_NAME,
  parameters: {
    layout: 'centered',
  },
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof meta>;

export const Default: Story = {
  args: {},
};

export const WithContent: Story = {
  args: {
    children: 'Sample content',
  },
};
EOF

        log_success "Created: $output_dir/$COMPONENT_NAME.stories.tsx"
    fi

    echo ""
    log_success "Component $COMPONENT_NAME generated successfully!"
    echo ""
    log_info "Import with:"
    echo "  import { $COMPONENT_NAME } from '@/components/$CATEGORY/$COMPONENT_NAME';"
}

show_usage() {
    echo "Usage: $0 <name> [options]"
    echo ""
    echo "Arguments:"
    echo "  name                          Component name (PascalCase)"
    echo ""
    echo "Options:"
    echo "  --category <feature|ui|layout> Component category (default: feature)"
    echo "  --with-test                    Generate test file"
    echo "  --with-story                   Generate Storybook story"
    echo "  --path <dir>                   Custom output path (relative to src/)"
    echo ""
    echo "Examples:"
    echo "  $0 FlowEpicCard"
    echo "  $0 Button --category ui --with-test --with-story"
    echo "  $0 DashboardLayout --category layout"
}

main() {
    parse_args "$@"

    # Validate component name (PascalCase)
    if [[ ! "$COMPONENT_NAME" =~ ^[A-Z][a-zA-Z0-9]*$ ]]; then
        log_error "Component name must be PascalCase (e.g., FlowEpicCard)"
        exit 1
    fi

    generate_component
}

main "$@"
