#!/bin/bash
#
# generate-hook.sh — SpaceOS React Hook Generator
# Part of SpaceOS Code Generator Toolchain (ADR-050 Phase 4.5)
#
# Usage:
#   ./generate-hook.sh <name> [options]
#
# Options:
#   --type <query|mutation|state|effect>   Hook type (default: query)
#   --with-test                            Include test file
#   --with-cache                           Add TanStack Query caching
#   --endpoint <path>                      API endpoint for query/mutation hooks
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPACEOS_ROOT="/opt/spaceos"
HOOKS_DIR="$SPACEOS_ROOT/datahaven-web/client/src/hooks"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Default values
HOOK_NAME=""
HOOK_TYPE="query"
WITH_TEST=false
WITH_CACHE=false
ENDPOINT=""

show_usage() {
    echo -e "${CYAN}SpaceOS Hook Generator${NC}"
    echo ""
    echo "Usage: $0 <name> [options]"
    echo ""
    echo "Arguments:"
    echo "  name                            Hook name (camelCase, without 'use' prefix)"
    echo ""
    echo "Options:"
    echo "  --type <query|mutation|state|effect>   Hook type (default: query)"
    echo "  --with-test                            Include test file"
    echo "  --with-cache                           Add TanStack Query caching (query/mutation only)"
    echo "  --endpoint <path>                      API endpoint path (e.g., /api/orders)"
    echo ""
    echo "Examples:"
    echo "  $0 Orders --type query --with-cache --endpoint /api/orders"
    echo "  $0 Auth --type state --with-test"
    echo "  $0 CreateQuote --type mutation --endpoint /api/quotes"
    echo "  $0 WindowResize --type effect"
}

parse_args() {
    if [ $# -lt 1 ]; then
        show_usage
        exit 1
    fi

    # Handle --help/-h as first argument
    if [[ "$1" == "--help" || "$1" == "-h" ]]; then
        show_usage
        exit 0
    fi

    HOOK_NAME="$1"
    shift

    while [ $# -gt 0 ]; do
        case "$1" in
            --type)
                HOOK_TYPE="$2"
                if [[ ! "$HOOK_TYPE" =~ ^(query|mutation|state|effect)$ ]]; then
                    log_error "Invalid hook type: $HOOK_TYPE. Must be query, mutation, state, or effect."
                    exit 1
                fi
                shift 2
                ;;
            --with-test)
                WITH_TEST=true
                shift
                ;;
            --with-cache)
                WITH_CACHE=true
                shift
                ;;
            --endpoint)
                ENDPOINT="$2"
                shift 2
                ;;
            -h|--help)
                show_usage
                exit 0
                ;;
            *)
                log_error "Unknown option: $1"
                show_usage
                exit 1
                ;;
        esac
    done
}

# Generate query hook with TanStack Query
generate_query_hook() {
    local hook_file="$HOOKS_DIR/use${HOOK_NAME}.ts"
    local api_endpoint="${ENDPOINT:-/api/${HOOK_NAME,,}s}"

    if [ "$WITH_CACHE" = true ]; then
        cat > "$hook_file" << EOF
/**
 * use${HOOK_NAME} - Query hook with TanStack Query caching
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { useQuery, UseQueryOptions } from '@tanstack/react-query';

export interface ${HOOK_NAME}Data {
  id: string;
  // TODO: Add your data properties
}

export interface Use${HOOK_NAME}Options {
  enabled?: boolean;
  refetchInterval?: number;
}

const fetch${HOOK_NAME} = async (): Promise<${HOOK_NAME}Data[]> => {
  const response = await fetch('${api_endpoint}', {
    credentials: 'include',
  });

  if (!response.ok) {
    throw new Error(\`Failed to fetch ${HOOK_NAME}: \${response.status}\`);
  }

  return response.json();
};

export const use${HOOK_NAME} = (options: Use${HOOK_NAME}Options = {}) => {
  const { enabled = true, refetchInterval } = options;

  return useQuery({
    queryKey: ['${HOOK_NAME,,}'],
    queryFn: fetch${HOOK_NAME},
    enabled,
    refetchInterval,
    staleTime: 5 * 60 * 1000, // 5 minutes
    gcTime: 30 * 60 * 1000, // 30 minutes (formerly cacheTime)
  });
};

export default use${HOOK_NAME};
EOF
    else
        cat > "$hook_file" << EOF
/**
 * use${HOOK_NAME} - Basic query hook
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { useState, useEffect } from 'react';

export interface ${HOOK_NAME}Data {
  id: string;
  // TODO: Add your data properties
}

export interface Use${HOOK_NAME}Result {
  data: ${HOOK_NAME}Data[] | null;
  isLoading: boolean;
  error: Error | null;
  refetch: () => void;
}

export const use${HOOK_NAME} = (): Use${HOOK_NAME}Result => {
  const [data, setData] = useState<${HOOK_NAME}Data[] | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState<Error | null>(null);

  const fetchData = async () => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch('${api_endpoint}', {
        credentials: 'include',
      });

      if (!response.ok) {
        throw new Error(\`Failed to fetch: \${response.status}\`);
      }

      const result = await response.json();
      setData(result);
    } catch (err) {
      setError(err instanceof Error ? err : new Error('Unknown error'));
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchData();
  }, []);

  return { data, isLoading, error, refetch: fetchData };
};

export default use${HOOK_NAME};
EOF
    fi

    log_success "Created: hooks/use${HOOK_NAME}.ts (query)"
}

# Generate mutation hook
generate_mutation_hook() {
    local hook_file="$HOOKS_DIR/use${HOOK_NAME}.ts"
    local api_endpoint="${ENDPOINT:-/api/${HOOK_NAME,,}}"

    if [ "$WITH_CACHE" = true ]; then
        cat > "$hook_file" << EOF
/**
 * use${HOOK_NAME} - Mutation hook with TanStack Query
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { useMutation, useQueryClient } from '@tanstack/react-query';

export interface ${HOOK_NAME}Params {
  // TODO: Add your mutation parameters
}

export interface ${HOOK_NAME}Result {
  id: string;
  // TODO: Add your result properties
}

const execute${HOOK_NAME} = async (params: ${HOOK_NAME}Params): Promise<${HOOK_NAME}Result> => {
  const response = await fetch('${api_endpoint}', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
    },
    credentials: 'include',
    body: JSON.stringify(params),
  });

  if (!response.ok) {
    throw new Error(\`${HOOK_NAME} failed: \${response.status}\`);
  }

  return response.json();
};

export const use${HOOK_NAME} = () => {
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: execute${HOOK_NAME},
    onSuccess: () => {
      // Invalidate related queries after successful mutation
      // TODO: Add queryKey to invalidate
      // queryClient.invalidateQueries({ queryKey: ['relatedData'] });
    },
    onError: (error) => {
      console.error('${HOOK_NAME} error:', error);
    },
  });
};

export default use${HOOK_NAME};
EOF
    else
        cat > "$hook_file" << EOF
/**
 * use${HOOK_NAME} - Basic mutation hook
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { useState, useCallback } from 'react';

export interface ${HOOK_NAME}Params {
  // TODO: Add your mutation parameters
}

export interface ${HOOK_NAME}Result {
  id: string;
  // TODO: Add your result properties
}

export interface Use${HOOK_NAME}Return {
  mutate: (params: ${HOOK_NAME}Params) => Promise<${HOOK_NAME}Result>;
  isLoading: boolean;
  error: Error | null;
  data: ${HOOK_NAME}Result | null;
  reset: () => void;
}

export const use${HOOK_NAME} = (): Use${HOOK_NAME}Return => {
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<Error | null>(null);
  const [data, setData] = useState<${HOOK_NAME}Result | null>(null);

  const mutate = useCallback(async (params: ${HOOK_NAME}Params): Promise<${HOOK_NAME}Result> => {
    setIsLoading(true);
    setError(null);

    try {
      const response = await fetch('${api_endpoint}', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        credentials: 'include',
        body: JSON.stringify(params),
      });

      if (!response.ok) {
        throw new Error(\`${HOOK_NAME} failed: \${response.status}\`);
      }

      const result = await response.json();
      setData(result);
      return result;
    } catch (err) {
      const error = err instanceof Error ? err : new Error('Unknown error');
      setError(error);
      throw error;
    } finally {
      setIsLoading(false);
    }
  }, []);

  const reset = useCallback(() => {
    setData(null);
    setError(null);
    setIsLoading(false);
  }, []);

  return { mutate, isLoading, error, data, reset };
};

export default use${HOOK_NAME};
EOF
    fi

    log_success "Created: hooks/use${HOOK_NAME}.ts (mutation)"
}

# Generate state hook with Zustand-like pattern
generate_state_hook() {
    local hook_file="$HOOKS_DIR/use${HOOK_NAME}.ts"

    cat > "$hook_file" << EOF
/**
 * use${HOOK_NAME} - State management hook
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { useState, useCallback, useMemo } from 'react';

export interface ${HOOK_NAME}State {
  // TODO: Add your state properties
  value: string;
  isOpen: boolean;
}

export interface Use${HOOK_NAME}Actions {
  setValue: (value: string) => void;
  setIsOpen: (isOpen: boolean) => void;
  toggle: () => void;
  reset: () => void;
}

export interface Use${HOOK_NAME}Return extends ${HOOK_NAME}State, Use${HOOK_NAME}Actions {}

const initial${HOOK_NAME}State: ${HOOK_NAME}State = {
  value: '',
  isOpen: false,
};

export const use${HOOK_NAME} = (initialState?: Partial<${HOOK_NAME}State>): Use${HOOK_NAME}Return => {
  const [state, setState] = useState<${HOOK_NAME}State>({
    ...initial${HOOK_NAME}State,
    ...initialState,
  });

  const setValue = useCallback((value: string) => {
    setState(prev => ({ ...prev, value }));
  }, []);

  const setIsOpen = useCallback((isOpen: boolean) => {
    setState(prev => ({ ...prev, isOpen }));
  }, []);

  const toggle = useCallback(() => {
    setState(prev => ({ ...prev, isOpen: !prev.isOpen }));
  }, []);

  const reset = useCallback(() => {
    setState(initial${HOOK_NAME}State);
  }, []);

  return useMemo(() => ({
    ...state,
    setValue,
    setIsOpen,
    toggle,
    reset,
  }), [state, setValue, setIsOpen, toggle, reset]);
};

export default use${HOOK_NAME};
EOF

    log_success "Created: hooks/use${HOOK_NAME}.ts (state)"
}

# Generate effect hook
generate_effect_hook() {
    local hook_file="$HOOKS_DIR/use${HOOK_NAME}.ts"

    cat > "$hook_file" << EOF
/**
 * use${HOOK_NAME} - Side effect hook
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { useEffect, useRef, useCallback } from 'react';

export interface Use${HOOK_NAME}Options {
  // TODO: Add your options
  enabled?: boolean;
  debounceMs?: number;
}

export interface Use${HOOK_NAME}Return {
  // TODO: Define return type based on your effect
}

export const use${HOOK_NAME} = (
  callback: () => void | (() => void),
  options: Use${HOOK_NAME}Options = {}
): Use${HOOK_NAME}Return => {
  const { enabled = true, debounceMs = 0 } = options;
  const callbackRef = useRef(callback);
  const timeoutRef = useRef<NodeJS.Timeout>();

  // Keep callback ref up to date
  useEffect(() => {
    callbackRef.current = callback;
  }, [callback]);

  useEffect(() => {
    if (!enabled) return;

    const execute = () => {
      const cleanup = callbackRef.current();
      return cleanup;
    };

    let cleanup: void | (() => void);

    if (debounceMs > 0) {
      timeoutRef.current = setTimeout(() => {
        cleanup = execute();
      }, debounceMs);
    } else {
      cleanup = execute();
    }

    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current);
      }
      if (typeof cleanup === 'function') {
        cleanup();
      }
    };
  }, [enabled, debounceMs]);

  // Return empty object - customize based on your needs
  return {} as Use${HOOK_NAME}Return;
};

export default use${HOOK_NAME};
EOF

    log_success "Created: hooks/use${HOOK_NAME}.ts (effect)"
}

# Generate test file
generate_test() {
    local test_file="$HOOKS_DIR/use${HOOK_NAME}.test.ts"

    cat > "$test_file" << EOF
/**
 * use${HOOK_NAME} - Test suite
 * Generated by SpaceOS Code Generator (ADR-050)
 */

import { renderHook, act, waitFor } from '@testing-library/react';
import { describe, it, expect, vi, beforeEach } from 'vitest';
import { use${HOOK_NAME} } from './use${HOOK_NAME}';

describe('use${HOOK_NAME}', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('should initialize with default state', () => {
    const { result } = renderHook(() => use${HOOK_NAME}());

    expect(result.current).toBeDefined();
    // TODO: Add your assertions
  });

  it('should handle state updates', async () => {
    const { result } = renderHook(() => use${HOOK_NAME}());

    // TODO: Add your test logic
    // act(() => {
    //   result.current.someAction();
    // });

    // await waitFor(() => {
    //   expect(result.current.someValue).toBe(expected);
    // });
  });

  it('should handle errors gracefully', async () => {
    // TODO: Add error handling tests
  });
});
EOF

    log_success "Created: hooks/use${HOOK_NAME}.test.ts"
}

main() {
    parse_args "$@"

    # Validate hook name (camelCase, no 'use' prefix)
    if [[ "$HOOK_NAME" =~ ^use ]]; then
        log_warn "Hook name should not start with 'use' - it will be added automatically"
        HOOK_NAME="${HOOK_NAME#use}"
    fi

    # Capitalize first letter
    HOOK_NAME="$(echo "${HOOK_NAME:0:1}" | tr '[:lower:]' '[:upper:]')${HOOK_NAME:1}"

    log_info "Generating ${HOOK_TYPE} hook: use${HOOK_NAME}"
    log_info "Output: $HOOKS_DIR/use${HOOK_NAME}.ts"

    # Ensure hooks directory exists
    mkdir -p "$HOOKS_DIR"

    # Generate based on type
    case "$HOOK_TYPE" in
        query)
            generate_query_hook
            ;;
        mutation)
            generate_mutation_hook
            ;;
        state)
            generate_state_hook
            ;;
        effect)
            generate_effect_hook
            ;;
    esac

    # Generate test if requested
    if [ "$WITH_TEST" = true ]; then
        generate_test
    fi

    echo ""
    log_success "Hook use${HOOK_NAME} generated successfully!"
    echo ""
    log_info "Next steps:"
    echo "  1. Open $HOOKS_DIR/use${HOOK_NAME}.ts"
    echo "  2. Update the interface types"
    echo "  3. Import: import { use${HOOK_NAME} } from '@/hooks/use${HOOK_NAME}'"
}

main "$@"
